```{r}
require(devtools)
require(annmatrix)
require(ggplot2)
require(ggplotify)
require(gurobi)
require(ggpubr)
require(patchwork)
require(parallel)
require(data.table)
require(stringr)
require(dplyr)
require(latex2exp)
require(annmatrix)
load_all()
source('plotConfig.R')
source('plot_template.R')
source('results/data/extract_data.R') 
get_legend <- function(p) {
   tmp <- ggplot_gtable(ggplot_build(p))
   leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
   legend <- tmp$grobs[[leg]]
   legend
}
slide_version_directory='/home/turner/research/ms_powerCHORD/srbr_talk/pres_figs/'
mc_cores=12
fsize=9
theme_set(theme_classic()) 
```

# Fig_motiv: Motivation from empirical histogram
## First part
```{r}
gen_panel_loc=function(mt){
  Nmeas =length(mt)
  mtdf=data.frame(time=mt)
  
  # panel 1 
  t_fine = seq(0,1,.005)
  freqs = c(1,4,9*.99)
  cp_levels = sort(24/freqs) %>% rev()
  cp_labels = round(cp_levels,2) %>%  {paste0(.,' hr')}
  phi_plt1=pi/2
  
  df = freqs %>% lapply(function(freq){
   data.frame(expr=cos(2*pi*freq*t_fine - phi_plt1),freq=freq,time=t_fine)
  }) %>% rbindlist() %>% data.frame()
  
  df_noise = freqs %>% lapply(function(freq){
   data.frame(expr=cos(2*pi*freq*mt - phi_plt1)+rnorm(length(mt)),
              freq=freq,time=mt)
  }) %>% rbindlist() %>% data.frame()
  df$circ_per=24/df$freq
  df$circ_per = factor(df$circ_per,cp_levels,cp_labels)
  df_noise$circ_per=24/df_noise$freq
  df_noise$circ_per = factor(df_noise$circ_per,cp_levels,cp_labels)
  df_noise = df_noise %>% mutate(T=circ_per)
  df= df%>% mutate(T=circ_per)
  p1=ggplot()+geom_line(data=df,aes(x=24*time,y=expr,group=circ_per,color=circ_per))+
    scale_color_manual(values = freq_colors)+
    geom_point(data=df_noise,aes(x=24*time,y=expr,color=circ_per),size=.5)+
    facet_wrap(~T,nrow=3,
               labeller = purrr::partial(label_both, sep = " = "))+
    labs(y='simulated signal',x='time (hr)')+
    scale_x_continuous(limits=c(0,24),breaks = 4*c(0:6))+
    scale_y_continuous(limits=c(-3,3),n.breaks=3)
 
  # panel 2 
  Nmc=1e2
  monteCarloPval <-function(tvec,Amp,freq,acro){
    Ydat = replicate(Nmc,{Amp*cos(2*pi*freq*tvec -acro) + rnorm(length(tvec))}) %>% t
    return(rowCosinor(Ydat,tvec,per=1/freq) %>% {.$pvalue} )
  }
  acrovec=seq(from=0,to=2*pi,.05)
  pars=expand.grid(freq=freqs,acro=acrovec)
  
  #TODO: better way of doing this
  df=c(1:dim(pars)[1]) %>% lapply(function(ind){
    x=pars[ind,]
    freq=as.numeric(x['freq'])
    acro=as.numeric(x['acro'])
    return(data.frame(freq=freq,acro=acro,
                      pvalue=monteCarloPval(mt,Amp,freq,acro)))
  }) %>% rbindlist() %>% data.frame()
  
  
  df$circ_per=24/df$freq
  df$circ_per = factor(df$circ_per,cp_levels,cp_labels)
  df = df %>% mutate(T=circ_per) 
  p2=df %>% ggplot(aes(x=acro,y=-log10(pvalue),color=circ_per))+
    geom_point(size=.5,alpha=.2)+
    facet_wrap(~T,nrow=3,
               labeller = purrr::partial(label_both, sep = " = "))+
    geom_hline(aes(yintercept =-log10(.05),linetype='p=0.05'),color='black')+
    scale_x_continuous(limits=c(0,2*pi),breaks =rad_brk,labels = rad_lab)+
    scale_y_continuous(limits =c(0,12),n.breaks = 2) +
    labs(x='acrophase (rad)',y='-log(pvalue)',linetype=element_blank())+
    scale_color_manual(values=freq_colors)+scale_linetype_manual(values=c('dashed'))+guides(color='none')
  plots=list()
  
  plots[[1]]=p1
  plots[[2]]=p2
  Fig=p1+p2 + plot_layout(guides='collect') & theme(legend.position='bottom',
     strip.background=element_blank(),
     text=element_text(size=fsize),
     plot.margin=margin(0,0,0,0),
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank(),
     axis.text.x = element_text(vjust = 0.25)
  )& labs(color='period')
 return(Fig) 
}


cols=viridisLite::viridisMap(3,begin=.3,end=.7,option='magma')
freq_colors=c(rgb(cols[1,c(1:3)]),rgb(cols[2,c(1:3)]),rgb(cols[3,c(1:3)]))
Nmeas = 18
mt_unif = c(1:Nmeas)/Nmeas-1/Nmeas

Amp = 3
Na  = 14
Nb  = Nmeas-Na
mta = c(1:Na)/Na-1/Na
mtb = c(1:Nb)/Nb-1/Nb
mt_alt  =c(mta/2,.5 + mtb/2) 

F1raw=gen_panel_loc(mt_unif)
F2raw=gen_panel_loc(mt_alt)
```

## Second part
```{r}
Amps = c(1,1.5,2)
Nacro=2^6+1
acros=seq(0,2*pi,length.out=Nacro)
acros=acros[1:(length(acros)-1)]

Nmvec = c(10,20,30)

Nfreq=2^8
freqs=seq(1,24,length.out=Nfreq)
pars=expand.grid(Amp=Amps,Nmeas=Nmvec,freq=freqs,acro=acros)

pars$power = c(1:dim(pars)[1]) %>% lapply(function(ii){
  x=pars[ii,]
  Amp   = x$Amp
  Nmeas = x$Nmeas
  acro  = x$acro
  freq  = x$freq
  mt = c(1:Nmeas)/Nmeas-1/Nmeas
  return(evalExactPower(mt,param=list(Amp=Amp,acro=acro,freq=freq)))
})

pars$power = as.numeric(pars$power)

pars =pars %>% mutate(A=Amp,N=Nmeas)
plt = pars %>% ggplot(aes(x=freq,y=acro,fill=power))+
  geom_raster()+
  facet_grid(A~N,labeller = purrr::partial(label_both, sep = " = "))+
  scale_y_continuous(limits=c(0,2*pi),breaks =rad_brk[c(1,3,5)],labels = rad_lab[c(1,3,5)])+
  scale_fill_viridis_c(limits=c(0,1))+
  labs(y='acrophase (rad)',x='frequency (cycles/day)')
```


## Combine
```{r}
Fig = ((F1raw[[1]]|F1raw[[2]]|F2raw[[1]]| F2raw[[2]])/plt)+
  plot_annotation(tag_levels=list(c('A','','B','','C')))+
  plot_layout(guides='collect') &theme(legend.position='bottom') + 
  theme(text=element_text(size=fsize),
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25)
  )
show_temp_plt(Fig,plt_width = 6,plt_height = 5)

plt_motivA       = F1raw[[1]]|F1raw[[2]]
plt_motivB       = F2raw[[1]]|F2raw[[2]]
plt_motivC       = plt
Fig_motiv        = Fig
Fig_motiv_width  = 6
Fig_motiv_height = 5
ggsave(paste0('~/research/ms_powerCHORD/figures/','motivation_fig_v2.png'),Fig_motiv,width=Fig_motiv_width,height=Fig_motiv_height,device='png',dpi=600)
```

# Fig_thresh: Performance of worst-case 

## Gain of power
```{r}
source('results/data/extract_fminfmax_data.R')
theme_set(theme_classic()) 
fdf$fmax = fdf$fmin+fdf$df

fdf = fdf %>% mutate(N=Nmeas)
plt = fdf %>% ggplot(aes(x=fmin,y=fmax,color=d_power))+geom_point(size=3)+
    facet_wrap(~N,labeller = purrr::partial(label_both, sep = " = "),nrow=1)+
  scale_color_viridis_c(limits=c(0,1)) 
plt_height = 3
plt_width  = 6

plt=plt+theme(text=element_text(size=fsize))

plt = plt + labs(x=element_text('min frequency (cycles/day)'),
                 y=element_text('max frequency (cycles/day)'),
                 color='gain of power')
plt
xmin=0
xmax=13
ymax=25
plt = plt + scale_x_continuous(limits =c(xmin,xmax),
                         breaks=seq(xmin,12,4),
                         labels=seq(xmin,12,4)) 

plt = plt + scale_y_continuous(limits =c(xmin,ymax),
                         breaks=seq(xmin,24,8),
                         labels=seq(xmin,24,8)) 

plt=plt+guides(fill=guide_colorbar(title.position='top'))
plt=plt+theme(legend.position='bottom',
               legend.key.width = unit(plt_width*.15, "in"),
               legend.title.align = 0.5,
               legend.direction = "horizontal")
plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25)
  )
plt

show_temp_plt(plt,plt_width,plt_height)
plt_GainWC = plt
```

## Distribution of measurement times 
```{r}
Nmeas_vals = c(24,48)
sloc = sols[sols@wreg==0&sols@drts==Inf,]
splt = sloc %>% stack()
splt = splt[splt$value<Inf,]

splt = splt %>% mutate(N=Nmeas)

plt=splt[splt$Nmeas %in% Nmeas_vals, ] %>% ggplot(aes(x=value,y=0))+geom_point(size=.5)+
  facet_grid(N~.,
             labeller = purrr::partial(label_both, sep = " = "))
plt = plt + theme(axis.title.y=element_blank()) 
plt = plt + theme(axis.text.y=element_blank()) 
plt = plt + labs(x=element_text('time (days)'))
plt = plt+scale_x_continuous(limits=c(0,1),breaks=c(0,1))
plt = plt+theme(axis.line.y = element_blank())
plt = plt+theme(axis.ticks.y = element_blank())
plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25)
  )

plt=plt+theme(text=element_text(size=9))
# make y-axis entire invisible

plt_width=6
plt_height=3
show_temp_plt(plt,plt_width,plt_height)

psol=plt
```

## Heatmaps
```{r}
Nfreq_plt=2^7
Nacro=2^5+1
acros=seq(0,2*pi,length.out=Nacro)
acros=acros[1:(length(acros)-1)]
freqs_plt = seq(1,24,length.out=Nfreq_plt)

pars=expand.grid(Amp=c(1),Nmeas=Nmeas_vals,acro=acros,freq=freqs_plt,type=c('equispaced design','threshold design'))

pwr_vec = c(1:dim(pars)[1]) %>% mclapply(mc.cores=mc_cores,function(ii){
  # unpack
  x      = pars[ii,]
  Nmeas  = as.numeric(x[['Nmeas']])
  acro   = as.numeric(x[['acro']])
  freq   = as.numeric(x[['freq']])
  Amp    = as.numeric(x[['Amp']]) 
  param =list(Amp=Amp,freq=freq,acro=acro) 
  
  if(x$type == 'equispaced design'){
    mt = c(1:Nmeas)/Nmeas-1/Nmeas 
  }else if(x$type =='threshold design'){
    mt=as.numeric(sloc[sloc@Nmeas==Nmeas,])
    mt=mt[mt<Inf]
  }else{
    stop('unknown type')
  }
  power=evalExactPower(mt,param)
  return(power)
})
pars$power = pwr_vec

pars$freq =as.numeric(pars$freq)
pars$acro =as.numeric(pars$acro)
pars$power=as.numeric(pars$power)

pars$N = factor(pars$Nmeas,unique(pars$Nmeas),paste0('N = ',unique(pars$Nmeas)))
plt = pars%>%
  ggplot(aes(x=freq,y=acro,fill=power))+
  geom_raster()+
  facet_grid(N~type)+
  scale_y_continuous(limits=c(0,2*pi),breaks =rad_brk[c(1,3,5)],labels = rad_lab[c(1,3,5)])+
  scale_fill_viridis_c(limits=c(0,1))+
  labs(y='acrophase (rad)',x='frequency (cycles/day)')

plt=plt+theme(legend.position='bottom',
               legend.key.width = unit(plt_width*.05, "in"),
               legend.title.align = 0.5,
               legend.direction = "horizontal")

plt=plt+guides(fill=guide_colorbar(title.position='left'))
plt=plt+theme(legend.position='bottom',
               legend.key.width = unit(plt_width*.15, "in"),
               legend.direction = "horizontal")
plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25)
  )
plt=plt+theme(text=element_text(size=9))
phmap = plt
phmap
```

## Combine
```{r}
#plt_GainWC_width  = plt_width
#plt_GainWC_height = plt_height
Fig_thresh = ((plt_GainWC&theme(legend.position = 'none'))/psol/phmap)+
  plot_layout(heights = c(1.5,1,1.25))+
  plot_annotation(tag_levels='A')

Fig_thresh_width=6
Fig_thresh_height=6

show_temp_plt(Fig_thresh,Fig_thresh_width,Fig_thresh_height)
ggsave(paste0('~/research/ms_powerCHORD/figures/','gain_of_non_unif.png'),Fig_thresh,width=Fig_thresh_width,height=Fig_thresh_height,device='png',dpi=600)

```

# Fig_trade: Tradeoff and comparison
```{r}
sloc = sols

Nmvals = sloc@Nmeas %>% unique()
source('results/data/extract_data.R')
freqs=seq(1,24,length.out=2^1)
unif_stats = Nmvals %>% lapply(function(Nm){
  mt = c(1:Nm)/Nm -1/Nm
  ncp=evalWorstNCP(mt,freqs=freqs,Amp=1)
  sc_afder=sqrt(evalAcroFreqGradL2(mt,
                     prior='uniform',
                     pars=list(fmin=min(freqs),fmax=max(freqs)),
                     Amp=1))/Nm
  
 data.frame(Nmeas= Nm,
            wreg = 0,
            drts = 'uniform',
            ncp  = ncp,
            sc_afder = sc_afder,
            stat_code = NaN,
            Nmeas_match = T,
            is_uniform = T) 
}) %>% rbindlist() %>% data.frame()


sloc@is_uniform = F
splt = rbind(sloc@'',unif_stats) 

splt$type = NaN
splt[splt$drts==6,]$type    = '1hr'
splt[splt$drts==12,]$type   = '2hr'
splt[splt$drts==18,]$type   = '3hr'
splt[splt$drts==Inf,]$type  = 'free'
splt[splt$is_uniform,]$type = 'equispaced'
```

```{r}
Nm_plt = seq(16,48,4)
plt=splt %>% mutate(N=Nmeas) %>% 
  filter(Nmeas %in% Nm_plt) %>% 
  ggplot(aes(x=ncp,y=-sc_afder,color=type,shape=wreg>0))+geom_point(size=1.5)+
  facet_wrap(~N,labeller = purrr::partial(label_both, sep = " = "))


plt = plt + labs(x=element_text('worst-case power score'),
                 y=element_text('negative regularization score'),
                 color='constraint',
                 shape='regularized')

plt=plt+theme(text=element_text(size=9))

plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25)
  )
Fig_trade = plt

Fig_trade_height = 3 
Fig_trade_width  = 6

show_temp_plt(plt,Fig_trade_width,Fig_trade_height)
ggsave(paste0('~/research/ms_powerCHORD/figures/','tradeoff.png'),Fig_trade,width=Fig_trade_width,height=Fig_trade_height,device='png',dpi=600)


```


# Fig_lomb : Lomb Scargle
```{r}
dfROC=readRDS('results/data/MCperiodogram/dfROC.RDS')
xmin=0
xmax=1

plt =dfROC %>% mutate(A=Amp,f=freq) %>% 
  filter(fdr_method=='BH',p_method=='std') %>% 
  ggplot(aes(x=FPR,y=TPR,group=type,color=type))+geom_line()+
  scale_x_continuous(limits = c(0,1))+
  facet_grid(A+p_osc~f,labeller=purrr::partial(label_both, sep = " = "))

plt = plt + scale_x_continuous(limits =c(xmin,xmax),breaks=c(0,1),labels=c(0,1)) +
  scale_y_continuous(limits=c(0,1))
plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25)
  )
plt=plt+theme(text=element_text(size=9))

plt=plt+labs(x=element_text('false positive rate'),
             y=element_text('true positive rate'),
             color=element_text('design'))

Fig =plt & theme(legend.position='bottom')

show_temp_plt(Fig,6,6)
```

```{r}
Fig_LS        = Fig
Fig_LS_width  = 6
Fig_LS_height = 6

ggsave(paste0('~/research/ms_powerCHORD/figures/','LombScargle_varp.png'),Fig_LS,width=Fig_LS_width,height=Fig_LS_height,device='png',dpi=600)

```

# Fig_regu_degen: Degeneracy

```{r}
Amp=1
# compute power with/without regularization
eval_reg_cfun = function(mt,freqs,w_reg){
  evalWorstNCP(mt,freqs,Amp=1)-
    w_reg*evalAcroFreqGradL2(mt,pars=list(fmin=min(freqs),fmax=max(freqs)))
}
```

```{r}
nt      = 60*2
Nfreq   = 2^7
Nm      = 24 
fmin    = 1 
fmaxs   = c(6,12,24)
mt_unif = c(1:Nm)/Nm - 1/Nm

ta_vals = seq(0,.5,length.out=nt)
tb_vals = seq(0,.5,length.out=nt)
pars    = expand.grid(ta=ta_vals,tb=tb_vals,fmax=fmaxs,wreg=c(0,1))

pars    = pars[pars$ta < pars$tb,]
pars    = pars[!(pars$ta %in% mt_unif),]
pars    = pars[!(pars$tb %in% mt_unif),]

pars$power = c(1:dim(pars)[1]) %>% mclapply(mc.cores=mc_cores,function(ii){
  x     = pars[ii,]
  ta    = x$ta %>% as.numeric()
  tb    = x$tb %>% as.numeric()
  fmax  = x$fmax %>% as.numeric()
  wreg  = x$wreg %>% as.numeric()
  
  mt    = c(mt_unif,ta,tb) 
  
  freqs = seq(fmin,fmax,length.out=Nfreq)
  
  return(eval_reg_cfun(mt,freqs,wreg))
})

pars$power = as.numeric(pars$power)
pars = pars %>% group_by(wreg,fmax) %>% 
  mutate(gmax = max(abs(power))) %>% ungroup()

pars = pars %>% group_by(wreg,fmax) %>% 
  mutate(power_norm = power/gmax) %>% ungroup()
```

```{r}
theme_set(theme_classic()) 

plt1=pars %>% filter(wreg==0) %>% ggplot(aes(x=ta,y=tb,fill=power_norm))+geom_raster()+scale_fill_viridis_c()+
  facet_wrap(~fmax,labeller = purrr::partial(label_both, sep = " = "),nrow=1)

plt2=pars %>% filter(wreg>0) %>% ggplot(aes(x=ta,y=tb,fill=power_norm))+geom_raster()+scale_fill_viridis_c()+
  facet_wrap(~fmax,labeller = purrr::partial(label_both, sep = " = "),nrow=1)

plt1 = plt1 & scale_x_continuous(limits =c(xmin,xmax),
                               breaks=c(xmin,xmax),
                               labels=round(c(xmin,xmax),2)) 
plt1 = plt1 & scale_y_continuous(limits =c(ymin,ymax),
                               breaks=c(ymin,ymax),
                               labels=round(c(ymin,ymax),2)) 
plt2 = plt2 & scale_x_continuous(limits =c(xmin,xmax),
                               breaks=c(xmin,xmax),
                               labels=round(c(xmin,xmax),2)) 
plt2 = plt2 & scale_y_continuous(limits =c(ymin,ymax),
                               breaks=c(ymin,ymax),
                               labels=round(c(ymin,ymax),2)) 



plt = plt1/plt2
plt
```

```{r}

plt=plt&theme(text=element_text(size=fsize))

xmin=0
xmax=.5
ymin=0
ymax=.5
plt_width = 6
plt_height=4

plt = plt & labs(x=TeX('$t_1$'),
                 y=TeX('$t_2$'),
                 fill='objective')

plt=plt&guides(fill=guide_colorbar(title.position='right'))
plt=plt&theme(legend.key.height = unit(plt_height*.06, "in"),
               legend.title = element_text(angle = 90),
               legend.title.align = 0.5,
               legend.direction = "vertical")

plt = plt & theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25))


plt = plt + plot_annotation(tag_levels='A')
plt_degen = plt
show_temp_plt(plt,plt_width,plt_height)
ggsave(paste0('~/research/ms_powerCHORD/figures/','degeneracy.png'),plt_degen,width=plt_width,height=plt_height,device='png',dpi=600)
```

# Fig_regu:  Pure regularization
## Raw solutions 
```{r}
scale=1.4
tau   = c(1:Nfine)/Nfine -1/Nfine 

Nfine = floor(144*scale/3)
Nmeas = floor(40*scale)
fmax  = 45
fmin_vals = c(1,10,20)
sols = c(1:length(fmin_vals)) %>% lapply(function(ii){
  fmin = fmin_vals[ii]
  sol=powerChord(Nmeas       = Nmeas,
                 drts        = Inf,
                 w_reg       = 1,
                 Nfreq       = 8,
                 num_threads = 12,
                 tlim        = 10,
                 Nfine       = Nfine,
                 w_wc        = 0,
                 fmin        = fmin,
                 fmax        = fmax,
                 MIPGap      = 1e-12
                 ) 
  return(data.frame(fmin=fmin,mt=tau[sol$x[1:Nfine]>0]))
}) %>% rbindlist() %>% data.frame()
head(sols)

plt = sols %>% ggplot(aes(x=mt,y=1))+geom_point(size=1)+
  facet_wrap(~fmin,labeller=purrr::partial(label_both, sep = " = "),nrow=3)+
  scale_x_continuous(limits=c(0,1))
plt = plt + theme(axis.title.y=element_blank()) 

plt = plt + theme(axis.text.y=element_blank()) 
plt = plt + labs(x=element_text('time (days)'))
plt = plt+scale_x_continuous(limits=c(0,1),breaks=c(0,1))
plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25)
  )
plt = plt+theme(axis.line.y = element_blank())
plt = plt+theme(axis.ticks.y = element_blank())
plt=plt+theme(text=element_text(size=9))
plt_raw = plt
plt_raw 
```

## Applicability 
```{r}
pdf = readRDS('results/data/pure_reg.RDS')
pdf = pdf %>% mutate(outcome = ifelse(status=='TIME_LIMIT','time_out',is_unif))
pdf = pdf %>% filter(cfactor<=2)
pdf$outcome = factor(pdf$outcome,c(T,F,'time_out'),c('equispaced optimal','irregular optimal','timeout'))
plt = pdf %>% mutate(c=cfactor) %>% ggplot(aes(x=Nmeas,y=fmax,fill=outcome))+ geom_raster()+
  facet_wrap(~c,labeller=purrr::partial(label_both, sep = " = "))


plt_height = 2.25
plt_width  = 6

# theme
theme_set(theme_classic()) 

# font size

plt = plt + labs(x=element_text('measurement budget'),
                 y=element_text('max frequency (cycles/day)'))
plt=plt+guides(fill=guide_legend(title.position='top'))
plt=plt+theme(legend.position='bottom',
               legend.key.width = unit(plt_width*.05, "in"),
               legend.title.align = 0.5,
               legend.direction = "horizontal",
                text = element_text(size=9))
# misc visuals
plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25)
)
plt=plt+theme(text=element_text(size=9))


plt_app = plt

plt_app
```

## Combine
```{r}
plt_width =6 
plt_height=5
plt_raw = plt_raw
plt_app = plt_app
Fig = plt_raw/plt_app  + plot_annotation(tag_levels='A')+
  plot_layout(heights=c(1.5,2))
show_temp_plt(Fig,plt_width,plt_height)
ggsave(paste0('~/research/ms_powerCHORD/figures/','pure_regularization.png'),Fig,width=plt_width,height=plt_height,device='png',dpi=600)
```