```{r}
require(devtools)
require(ggplot2)
require(annmatrix)
require(ggplotify)
require(patchwork)
require(parallel)
require(data.table)
require(stringr)
require(dplyr)
require(latex2exp)
require(annmatrix)
load_all()
source('plotConfig.R')
source('results/data/extract_data.R') 

#slide_version_directory='/home/turner/research/misc_tex/committee_meeting/figs/'
mc_cores=8
```

# Motivation: empirical p-values
```{r}
gen_panel_loc=function(mt){
  Nmeas =length(mt)
  mtdf=data.frame(time=mt)
  
  # panel 1 
  t_fine = seq(0,1,.005)
  freqs = c(1,4,9*.99)
  cp_levels = sort(24/freqs) %>% rev()
  cp_labels = round(cp_levels,2) %>%  {paste0(.,' hr')}
  phi_plt1=pi/2
  
  df = freqs %>% lapply(function(freq){
   data.frame(expr=cos(2*pi*freq*t_fine - phi_plt1),freq=freq,time=t_fine)
  }) %>% rbindlist() %>% data.frame()
  
  df_noise = freqs %>% lapply(function(freq){
   data.frame(expr=cos(2*pi*freq*mt - phi_plt1)+rnorm(length(mt)),
              freq=freq,time=mt)
  }) %>% rbindlist() %>% data.frame()
  df$circ_per=24/df$freq
  df$circ_per = factor(df$circ_per,cp_levels,cp_labels)
  df_noise$circ_per=24/df_noise$freq
  df_noise$circ_per = factor(df_noise$circ_per,cp_levels,cp_labels)
  p1=ggplot()+geom_line(data=df,aes(x=24*time,y=expr,group=circ_per,color=circ_per))+
    scale_color_manual(values = freq_colors)+
    geom_point(data=df_noise,aes(x=24*time,y=expr,color=circ_per),size=.5)+
    facet_wrap(~circ_per,nrow=3)+
    labs(y='simulated signal',x='measurement time (hr)')+
    scale_x_continuous(limits=c(0,24),breaks = 4*c(0:6))+
    scale_y_continuous(limits=c(-3,3),n.breaks=3)
 
  # panel 2 
  Nmc=1e2
  monteCarloPval <-function(tvec,Amp,freq,acro){
    Ydat = replicate(Nmc,{Amp*cos(2*pi*freq*tvec -acro) + rnorm(length(tvec))}) %>% t
    return(rowCosinor(Ydat,tvec,per=1/freq) %>% {.$pvalue} )
  }
  acrovec=seq(from=0,to=2*pi,.05)
  pars=expand.grid(freq=freqs,acro=acrovec)
  
  #TODO: better way of doing this
  df=c(1:dim(pars)[1]) %>% lapply(function(ind){
    x=pars[ind,]
    freq=as.numeric(x['freq'])
    acro=as.numeric(x['acro'])
    return(data.frame(freq=freq,acro=acro,
                      pvalue=monteCarloPval(mt,Amp,freq,acro)))
  }) %>% rbindlist() %>% data.frame()
  
  
  df$circ_per=24/df$freq
  df$circ_per = factor(df$circ_per,cp_levels,cp_labels)
   
  p2=df %>% ggplot(aes(x=acro,y=-log10(pvalue),color=circ_per))+
    geom_point(size=.5,alpha=.2)+
    facet_wrap(~circ_per,nrow=3)+
    geom_hline(aes(yintercept =-log10(.05),linetype='p=0.05'),color='black')+
    scale_x_continuous(limits=c(0,2*pi),breaks =rad_brk,labels = rad_lab)+
    scale_y_continuous(limits =c(0,12),n.breaks = 2) +
    labs(x='acrophase (rad)',y='-log(pvalue)',linetype=element_blank())+
    scale_color_manual(values=freq_colors)+scale_linetype_manual(values=c('dashed'))+guides(color='none')
  plots=list()
  
  plots[[1]]=p1
  plots[[2]]=p2
  Fig=p1+p2 + plot_layout(guides='collect') & theme(legend.position='bottom',
     strip.background=element_blank(),
     text=element_text(size=9),
     plot.margin=margin(0,0,0,0),
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank(),
     axis.text.x = element_text(vjust = 0.25)
  )& labs(color='period')
 return(Fig) 
}


cols=viridisLite::viridisMap(3,begin=.3,end=.7,option='magma')
freq_colors=c(rgb(cols[1,c(1:3)]),rgb(cols[2,c(1:3)]),rgb(cols[3,c(1:3)]))
Nmeas = 18
mt_unif = c(1:Nmeas)/Nmeas-1/Nmeas

Amp = 3
Na  = 14
Nb  = Nmeas-Na
mta = c(1:Na)/Na-1/Na
mtb = c(1:Nb)/Nb-1/Nb
mt_alt  =c(mta/2,.5 + mtb/2) 

F1raw=gen_panel_loc(mt_unif)
F2raw=gen_panel_loc(mt_alt)
F1=as.ggplot(F1raw&theme(legend.position = 'none'))
F2=as.ggplot(F2raw&theme(legend.position = 'bottom'))

Fig = F1/F2 + plot_annotation(tag_levels ='A')+plot_layout(guides='collect',heights = c(5,6.5))
ggsave(paste0('~/research/ms_powerCHORD/figures/','motivation_fig_v2.png'),Fig,width=6,height=6,device='png',dpi=600)

```

# Motivation: power variability

## First version of figure
```{r}
#Nfreq=2^8
#Nacro=2^6+1
#
#Nmeas=12
#mt = c(1:Nmeas)/Nmeas-1/Nmeas
#
#freqs=seq(1,24,length.out=Nfreq)
#acros=seq(0,2*pi,length.out=Nacro)
#acros=acros[1:(length(acros)-1)]
#
#Amps  = seq(1,2,.2)
#Nmvec = seq(10,30,2)
#
#pars=expand.grid(Amp=Amps,Nmeas=Nmvec)
#
#pars$delta = c(1:dim(pars)[1]) %>% mclapply(mc.cores = mc_cores,function(ind){
#  # unpack
#  x     = pars[ind,]
#  Nmeas = x$Nmeas
#  Amp   = x$Amp
#  mt    = c(1:Nmeas)/Nmeas-1/Nmeas
#
#  # for each freq, compute power variation 
#  delta_vec = rep(NaN,length(freqs)) 
#  for (fr_ind in c(1:length(freqs))){
#    freq_loc = freqs[fr_ind]
#    pwrs = sapply(acros,function(acro){
#      eval_exact_power(t=mt,param=list(Amp=Amp,acro=acro,freq=freq_loc))
#    }) 
#    delta_vec[fr_ind] = max(pwrs)-min(pwrs)
#  } 
#  return(max(abs(delta_vec)))
#})
#pars$delta=as.numeric(pars$delta)
#pars %>% ggplot(aes(x=Amp,y=Nmeas,fill=delta))+geom_raster()+
#  scale_fill_viridis_c(limits=c(0,1))
```

## Second version
```{r}
Amps  = seq(0.5,2,.05)
Nmvec = c(12,24,32)

Nacro=2^6+1
acros=seq(0,2*pi,length.out=Nacro)
acros=acros[1:(length(acros)-1)]

Nmeas=12
mt = c(1:Nmeas)/Nmeas-1/Nmeas

Nfreq=2^8
freqs=seq(1,24,length.out=Nfreq)
pars=expand.grid(Amp=Amps,Nmeas=Nmvec,freq=freqs)

delta_vec = c(1:dim(pars)[1]) %>% mclapply(mc.cores=mc_cores,function(ind){
  # unpack
  x     = pars[ind,] 
  Amp   = x$Amp
  Nmeas = x$Nmeas
  freq  = x$freq
  mt    = c(1:Nmeas)/Nmeas-1/Nmeas
  
  pwrs = sapply(acros,function(acro){
    eval_exact_power(t=mt,param=list(Amp=Amp,acro=acro,freq=freq))
  }) 
  return(max(pwrs)-min(pwrs))
})
pars$delta=as.numeric(delta_vec)

plt_raw =  pars %>% ggplot(aes(x=Amp,y=freq,fill=delta))+geom_raster()+facet_wrap(~Nmeas)+
  scale_fill_viridis_c(limits=c(0,1))


```

Aesthetics
```{r}
theme_set(theme_classic()) 
plt=plt_raw
plt_height = 3
plt_width  = 6

plt=plt+theme(text=element_text(size=9))

plt = plt + labs(x=element_text('amplitude'),
                 y=element_text('frequency (cycles/day)'),
                 fill ='power variation')

plt=plt+guides(fill=guide_colorbar(title.position='right'))
plt=plt+theme(legend.key.height = unit(plt_height*.15, "in"),
               legend.title = element_text(angle = 90),
               legend.title.align = 0.5,
               legend.direction = "vertical")

  
plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25)
  )

show_temp_plt(plt,plt_width,plt_height)
```

```{r}
ggsave(paste0('~/research/ms_powerCHORD/figures/','motivation_power_var.png'),plt,width=plt_width,height=plt_height,device='png',dpi=600)
```


# Result: Power heatmap
```{r}
wreg_val = 1 
drts_val = 12 
panel_filtA = sols@wreg==0        & sols@drts==Inf 
panel_filtB = sols@wreg==wreg_val & sols@drts==Inf 
panel_filtC = sols@wreg==0        & sols@drts==drts_val
panel_filtD = sols@wreg==wreg_val & sols@drts==drts_val

amp_vals = c(1,1.5)
Nmeas_vals = c(16,32)
Nfreq_plt=2^7
Nacro=2^5+1
acros=seq(0,2*pi,length.out=Nacro)
acros=acros[1:(length(acros)-1)]
freqs_plt = seq(1,26,length.out=Nfreq_plt)

pars=expand.grid(Amp=amp_vals,Nmeas=Nmeas_vals,acro=acros,freq=freqs_plt)
make_panel = function(sols,pfilt,pars){
  sloc = sols[pfilt,]
  pwr2df = c(1:dim(pars)[1]) %>%
    mclapply(mc.cores=mc_cores,function(ii){
    # unpack
    x      = pars[ii,]
    Nmeas  = as.numeric(x[['Nmeas']])
    acro   = as.numeric(x[['acro']])
    freq   = as.numeric(x[['freq']])
    Amp    = as.numeric(x[['Amp']]) 
    param =list(Amp=Amp,freq=freq,acro=acro) 
  
    mt=as.numeric(sloc[sloc@Nmeas==Nmeas,])
    mt=mt[mt<Inf]
     
    power=eval_exact_power(mt,param)
    return(data.frame(acro=acro,freq=freq,power=power,Nmeas=Nmeas,Amp=Amp))
  }) %>% rbindlist() %>% data.frame()
 
  
  return(pwr2df %>% ggplot(aes(x=freq,y=acro,fill=power))+geom_raster()+
  facet_grid(Amp~Nmeas)+
  scale_y_continuous(limits=c(0,2*pi),breaks =rad_brk[c(1,3,5)],labels = rad_lab[c(1,3,5)])+
  scale_fill_viridis_c(limits=c(0,1))+
  labs(y='acrophase (rad)',x='frequency (cycles/day)'))
}


pA_pwr = make_panel(sols,panel_filtA,pars)
pB_pwr = make_panel(sols,panel_filtB,pars)
pC_pwr = make_panel(sols,panel_filtC,pars)
pD_pwr = make_panel(sols,panel_filtD,pars)

make_soln_panel=function(sols,pfilt,pars){
  sloc = sols[pfilt & (sols@Nmeas %in% pars$Nmeas),]
  mt_long = sloc %>% stack()
  mt_long = mt_long[mt_long$value<Inf,]
  return(mt_long %>% ggplot(aes(x=value,y=1))+geom_point(size=.5)+
    xlim(c(0,1))+theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      axis.text.y = element_blank() 
    )+
    facet_wrap(~Nmeas,nrow=1))
}
pA_sol = make_soln_panel(sols,panel_filtA,pars)
pB_sol = make_soln_panel(sols,panel_filtB,pars)
pC_sol = make_soln_panel(sols,panel_filtC,pars)
pD_sol = make_soln_panel(sols,panel_filtD,pars)

assemble_panel = function(ptop,pbottom){
  as.ggplot(ptop/pbottom+ plot_layout(heights=c(2,10)) &
     theme(
       legend.position='none',
       strip.background=element_blank(),
       text=element_text(size=fs_glob),
       plot.margin=margin(0,0,0,0),
       panel.grid.major = element_blank(),
       panel.grid.minor = element_blank(),
       axis.text.x = element_text(vjust = 0.25)
    ))
}

pA = assemble_panel(pA_sol,pA_pwr) 
pB = assemble_panel(pB_sol,pB_pwr) 
pC = assemble_panel(pC_sol,pC_pwr) 
pD = assemble_panel(pD_sol,pD_pwr) 
fs_glob=9
(pA+pB)/(pC+pD)
```

# Result: Power heatmap

# Result: Regularised/constrained heatmap

# Result: Performance and convergence
```{r}
sols_plt = sols[sols@wreg %in% c(0,1),]
sols_plt@''%>% 
  ggplot(aes(x=Nmeas,y=ncp,
             shape=as.factor(wreg),color=as.factor(drts)))+
  geom_point(size=2)+
  facet_wrap(~stat_code)
```

# Result: Gain of non-uniformity

# Result: Non-uniqueness of maximizers