```{r}
fs=20
slide_dir = '/home/turner/research/ms_powerCHORD/srbr_talk/pres_figs/'
require(devtools)
require(annmatrix)
require(ggplot2)
require(ggplotify)
require(gurobi)
require(ggpubr)
require(patchwork)
require(parallel)
require(data.table)
require(stringr)
require(dplyr)
require(latex2exp)
require(annmatrix)
load_all()
source('plotConfig.R')
source('plot_template.R')
source('results/data/extract_data.R') 
get_legend <- function(p) {
   tmp <- ggplot_gtable(ggplot_build(p))
   leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
   legend <- tmp$grobs[[leg]]
   legend
}
mc_cores=12
fsize=9
theme_set(theme_classic()) 

cmap = c('balanced'='#40826E',
         'threshold'='#A60A5E',
         'random' ='#003399',
         'equispaced'='black'
         )
```

# Framework
```{r}
t = seq(0,1,.001)

yfast = cos(2*pi*8*t)
yslow = sin(2*pi*1*t)
mtslow = c(1:6)/6-1/6
mtfast = (c(1:6)/6-1/6)/4

df_sig=rbind(data.frame(t=t,sig=yfast-4,type='fast'),data.frame(t=t,sig=yslow+4,type='slow'))
df_mt = rbind(data.frame(mt=mtfast,type='fast',y=-6),data.frame(mt=mtslow,type='slow',y=2))

p_cert = ggplot()+
  geom_point(data=df_mt,aes(x=mt,y=y,color=type),size=3)+xlim(c(0,1))+
  geom_line(data=df_sig,aes(x=t,y=sig,group=type,color=type))+scale_color_manual(values = c('fast'='red','slow'='blue'))+theme(legend.position='none')


mt_irr = c(mtfast[1:3],mtslow[4:6]-1/6)
df_mt = rbind(data.frame(mt=mt_irr[1:3],type='fastp',y=0),
              data.frame(mt=mt_irr[4:6],type='slowp',y=0)
              )
p_uncert =  ggplot()+xlim(c(0,1))+
  geom_line(data=df_sig,aes(x=t,y=sig,group=type,color=type))+scale_color_manual(values = c('fast'=rgb(.44,.44,.44),'slow'=rgb(.44,.44,.44),'fastp'='red','slowp'='blue'))+theme(legend.position='none')


plt=(p_cert + p_uncert)+plot_annotation(tag_levels="A")
plt=plt&theme(axis.text.x=element_blank())
plt=plt&theme(axis.text.y=element_blank())
plt=plt&theme(axis.ticks.x=element_blank())
plt=plt&theme(axis.ticks.y=element_blank())
plt=plt & labs(x=element_text('time'),
                 y=element_blank())
plt=plt&theme(text=element_text(size=fs))

ggsave(paste0(slide_dir,'framework1.png'),plt,width=12,height=7,device='png',dpi=600)
```


```{r}
p_uncert =  ggplot()+
  geom_point(data=df_mt,aes(x=mt,y=y,color=type),size=3)+xlim(c(0,1))+
  geom_line(data=df_sig,aes(x=t,y=sig,group=type,color=type))+scale_color_manual(values = c('fast'=rgb(.44,.44,.44),'slow'=rgb(.44,.44,.44),'fastp'='red','slowp'='blue'))+theme(legend.position='none')


plt=(p_cert + p_uncert)+plot_annotation(tag_levels="A")
plt=plt&theme(axis.text.x=element_blank())
plt=plt&theme(axis.text.y=element_blank())
plt=plt&theme(axis.ticks.x=element_blank())
plt=plt&theme(axis.ticks.y=element_blank())
plt=plt & labs(x=element_text('time'),
                 y=element_blank())
plt=plt&theme(text=element_text(size=fs))

ggsave(paste0(slide_dir,'framework2.png'),plt,width=12,height=7,device='png',dpi=600)

```

# Trimmed version of empirical p-val 
```{r}
gen_panel_loc=function(mt){
  Nmeas =length(mt)
  mtdf=data.frame(time=mt)
  
  # panel 1 
  t_fine = seq(0,1,.005)
  freqs = c(1,4,9*.99)
  cp_levels = sort(24/freqs) %>% rev()
  cp_labels = round(cp_levels,2) %>%  {paste0(.,' hr')}
  phi_plt1=pi/2
  
  df = freqs %>% lapply(function(freq){
   data.frame(expr=cos(2*pi*freq*t_fine - phi_plt1),freq=freq,time=t_fine)
  }) %>% rbindlist() %>% data.frame()
  
  df_noise = freqs %>% lapply(function(freq){
   data.frame(expr=cos(2*pi*freq*mt - phi_plt1)+rnorm(length(mt)),
              freq=freq,time=mt)
  }) %>% rbindlist() %>% data.frame()
  df$circ_per=24/df$freq
  df$circ_per = factor(df$circ_per,cp_levels,cp_labels)
  df_noise$circ_per=24/df_noise$freq
  df_noise$circ_per = factor(df_noise$circ_per,cp_levels,cp_labels)
  df_noise = df_noise %>% mutate(T=circ_per)
  df= df%>% mutate(T=circ_per)
  p1=ggplot()+geom_line(data=df,aes(x=24*time,y=expr,group=circ_per,color=circ_per))+
    scale_color_manual(values = freq_colors)+
    geom_point(data=df_noise,aes(x=24*time,y=expr,color=circ_per),size=2)+
    facet_wrap(~T,nrow=3,
               labeller = purrr::partial(label_both, sep = " = "))+
    labs(y='simulated signal',x='time (hr)')+
    scale_x_continuous(limits=c(0,24),breaks = 4*c(0:6))+
    scale_y_continuous(limits=c(-3,3),n.breaks=3)
 
  # panel 2 
  Nmc=1e2
  monteCarloPval <-function(tvec,Amp,freq,acro){
    Ydat = replicate(Nmc,{Amp*cos(2*pi*freq*tvec -acro) + rnorm(length(tvec))}) %>% t
    return(rowCosinor(Ydat,tvec,per=1/freq) %>% {.$pvalue} )
  }
  acrovec=seq(from=0,to=2*pi,.05)
  pars=expand.grid(freq=freqs,acro=acrovec)
  
  df=c(1:dim(pars)[1]) %>% lapply(function(ind){
    x=pars[ind,]
    freq=as.numeric(x['freq'])
    acro=as.numeric(x['acro'])
    return(data.frame(freq=freq,acro=acro,
                      pvalue=monteCarloPval(mt,Amp,freq,acro)))
  }) %>% rbindlist() %>% data.frame()
  
  
  df$circ_per=24/df$freq
  df$circ_per = factor(df$circ_per,cp_levels,cp_labels)
  df = df %>% mutate(T=circ_per) 
  p2=df %>% ggplot(aes(x=acro,y=-log10(pvalue),color=circ_per))+
    geom_point(size=.5,alpha=.2)+
    facet_wrap(~T,nrow=3,
               labeller = purrr::partial(label_both, sep = " = "))+
    geom_hline(aes(yintercept =-log10(.05),linetype='p=0.05'),color='black')+
    scale_x_continuous(limits=c(0,2*pi),breaks =rad_brk,labels = rad_lab)+
    scale_y_continuous(limits =c(0,12),n.breaks = 2) +
    labs(x='acrophase (rad)',y='-log(pvalue)',linetype=element_blank())+
    scale_color_manual(values=freq_colors)+scale_linetype_manual(values=c('dashed'))+guides(color='none')
  plots=list()
  
  plots[[1]]=p1
  plots[[2]]=p2
  Fig=p1+p2 + plot_layout(guides='collect') & theme(legend.position='bottom',
     strip.background=element_blank(),
     text=element_text(size=fsize),
     plot.margin=margin(0,0,0,0),
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank(),
     axis.text.x = element_text(vjust = 0.25)
  )& labs(color='period')
 return(Fig) 
}


cols=viridisLite::viridisMap(3,begin=.3,end=.7,option='magma')
freq_colors=c(rgb(cols[1,c(1:3)]),rgb(cols[2,c(1:3)]),rgb(cols[3,c(1:3)]))
Nmeas = 18
mt_unif = c(1:Nmeas)/Nmeas-1/Nmeas

Amp = 3
Na  = 14
Nb  = Nmeas-Na
mta = c(1:Na)/Na-1/Na
mtb = c(1:Nb)/Nb-1/Nb
mt_alt  =c(mta/2,.5 + mtb/2) 

F1raw=gen_panel_loc(mt_unif)
F2raw=gen_panel_loc(mt_alt)
```


## Combine
```{r}
Fig = ((F1raw[[1]]|F1raw[[2]]|F2raw[[1]]| F2raw[[2]]))+
  plot_annotation(tag_levels=list(c('A','','B','')))+
  plot_layout(guides='collect') &theme(legend.position='bottom',
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  text=element_text(size=fs),
  axis.title.x=element_text(size=fs),
  axis.text=element_text(size=12),
  axis.title.y=element_text(size=fs),
  axis.text.x = element_text(vjust = 0.25)
  )
Fig
show_temp_plt(Fig,12,8)
ggsave(paste0(slide_dir,'motivation_fig.png'),Fig,width=12,height=7,device='png',dpi=600)
```

# Trimmed gain slide
```{r}

source('results/data/extract_fminfmax_data.R')
theme_set(theme_classic()) 
fdf$fmax = fdf$fmin+fdf$df

fdf = fdf %>% mutate(N=Nmeas)
plt = fdf %>% ggplot(aes(x=fmin,y=fmax,color=d_power))+geom_point(size=5)+
    facet_wrap(~N,labeller = purrr::partial(label_both, sep = " = "),nrow=1)+
  scale_color_viridis_c(limits=c(0,1)) 
plt_height = 3
plt_width  = 6


plt = plt + labs(x=element_text('min frequency (cycles/day)'),
                 y=element_text('max frequency (cycles/day)'),
                 color='gain of power')
plt
xmin=0
xmax=13
ymax=25
plt = plt + scale_x_continuous(limits =c(xmin,xmax),
                         breaks=seq(xmin,12,4),
                         labels=seq(xmin,12,4)) 

plt = plt + scale_y_continuous(limits =c(xmin,ymax),
                         breaks=seq(xmin,24,8),
                         labels=seq(xmin,24,8)) 

plt=plt+guides(fill=guide_colorbar(title.position='top'))
plt=plt+theme(legend.position='bottom',
               legend.key.width = unit(plt_width*.15, "in"),
               legend.title.align = 0.5,
               legend.direction = "horizontal")
plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  text=element_text(size=fs),
  axis.title.x=element_text(size=fs),
  axis.title.y=element_text(size=fs),
  axis.text.x = element_text(vjust = 0.25)
  )
plt

show_temp_plt(plt,10,5)
plt_GainWC = plt

ggsave(paste0(slide_dir,'gain_of_power.png'),plt_GainWC,width=10,height=5,device='png',dpi=600)

```


# Single row of periodogram
```{r}
dfROC=readRDS('results/data/MCperiodogram/dfROC.RDS')
xmin=0
xmax=1

cmap = c('balanced'=rgb(0,.5,1),
         'threshold'=rgb(1.0, 0.13, 0.32),
         'random' ='#003399',
         'equispaced'='black'
         )

plt =dfROC %>% mutate(A=Amp,f=freq) %>% filter(A==1 & p_osc==.5 & type!='random') %>%  
  filter(fdr_method=='BH',p_method=='std') %>% 
  ggplot(aes(x=FPR,y=TPR,group=type,color=type))+geom_line(size=1.5)+
  scale_x_continuous(limits = c(0,1))+
  facet_wrap(~f,labeller=purrr::partial(label_both, sep = " = "))
plt=plt+scale_color_manual(values=cmap)

plt = plt + scale_x_continuous(limits =c(xmin,xmax),breaks=c(0,1),labels=c(0,1)) +
  scale_y_continuous(limits=c(0,1))
plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  text=element_text(size=fs),
  axis.title.x=element_text(size=fs),
  axis.title.y=element_text(size=fs),
  axis.text.x = element_text(vjust = 0.25)
  )

plt=plt+labs(x=element_text('false positive rate'),
             y=element_text('true positive rate'),
             color=element_text('design'))

Fig =plt & theme(legend.position='bottom')

show_temp_plt(Fig,8,6)
ggsave(paste0(slide_dir,'plomb.png'),Fig,width=10,height=6,device='png',dpi=600)

```