```{r}
library(stats)
library(dplyr)
library(ggplot2)
library(gurobi)
library(CVXR)
library(dplyr)
library(expm)
library(patchwork)
```
# Test problems 

## Min_entries
Should assign weight to the lowest two entries
```{r}
# check that min_entries works in the way you'd expect 
Nfine        = 2^2
Nmeas        = 2^1 
x            = Variable(Nfine,boolean=T)
constraints  = list( sum(x) == Nmeas)

bvec         = runif(Nfine)

objective    = min_entries(bvec+x)
prob         = Problem(Maximize(objective),constraints)
result       = solve(prob,verbose=T)

bvec
result$getValue(objet=x)
```

## Min_entries with real cfun


```{r}
Nfine        = 2^6
Nfreq        = 2^2
Nmeas        = 24 
x            = Variable(Nfine,boolean=T)
constraints  = list( sum(x) == Nmeas)

tau   = (0:Nfine)/Nfine       
tau   = tau[1:(length(tau)-1)] 
fmin  = 1
fmax  = 24 
fvec  = seq(from=fmin,to=fmax,length.out=Nfreq)

cmat   = cos(2*pi*outer(fvec,tau))
smat   = sin(2*pi*outer(fvec,tau))
(cmat*cmat)%*%x
(cmat*cmat)%*%x

obj = (cmat*cmat)%*%(cmat[1,]*x)# *((smat*smat)%*%x) - ((cmat*smat)%*%x)*((cmat*smat)%*%x) 
prob         = Problem(Maximize(min_entries(obj)),constraints)
result       = solve(prob,verbose=T,num_iter=1e7)
result$getValue(objet=x)

```

```{r}
Nfine        = 2^6
Nfreq        = 2^2
Nmeas        = 24 
x            = Variable(Nfine,boolean=T)
constraints  = list( sum(x) == Nmeas)

tau   = (0:Nfine)/Nfine       
tau   = tau[1:(length(tau)-1)] 
fmin  = 1
fmax  = 24 
fvec  = seq(from=fmin,to=fmax,length.out=Nfreq)

#cmat   = cos(2*pi*outer(fvec,tau))
#smat   = sin(2*pi*outer(fvec,tau))
#(cmat*cmat)%*%x
#(cmat*cmat)%*%x
#((cmat*cmat)%*%x)*((smat*smat)%*%x) - ((cmat*smat)%*%x)*((cmat*smat)%*%x) 
##objective    = min_entries( multiply((cmat*cmat)%*%x,(smat*smat)%*%x))
#objective    = min_entries( norm2(cmat%*%x)^2*norm2(smat%*%x)^2)
for (freq in fvec ){
  cvec  = matrix(cos(2*pi*freq*tau),nrow=Nfine)
  svec  = matrix(sin(2*pi*freq*tau),nrow=Nfine)
  
  a11   = cvec*cvec
  a22   = svec*svec
  a12   = cvec*svec
  bvec  = a11+a22
  Amat  = a11%*%t(a11) + a22%*%t(a22) +4*a12%*%t(a12)-a11%*%t(a22) - a22%*%t(a11)
  A12   = Re(expm::sqrtm(Amat))
  if (freq==fmin){
    obj   = 0.5*(t(bvec)%*%x - CVXR::norm2(A12%*%x))
  }else{
    obj   = rbind(obj,0.5*(t(bvec)%*%x - CVXR::norm2(A12%*%x)))
  }
}

prob         = Problem(Maximize(min_entries(obj)),constraints)
result       = solve(prob,verbose=T,num_iter=1e7)
result$getValue(objet=x)

```


```{r}
eye = replicate(Nfine,{1}) %>% diag() %>% Constant()

prob         = Problem(Maximize(lambda_min(diag(x))),constraints)
result       = solve(prob,verbose=T,num_iter=1e7)
result$getValue(objet=x)
```


```{r}
Nfine        = 2^3
Nfreq        = 2^3 
Nmeas        = 24 
x            = Variable(Nfine,boolean=T)
constraints  = list( sum(x) == Nmeas)

n=10
expr = 0
for (ii in c(1:Nfine)){
  bv=10+runif(n)
  expr = expr + x[ii]*bv%*%t(bv) 
}
expr 
solve(Problem(Minimize(-CVXR::log_det(expr)),constraints))



```


# Testing min_elemwise

```{r}
Nfine        = 2^6
Nfreq        = 2^2
Nmeas        = 24 
x            = Variable(Nfine,boolean=T)
constraints  = list( sum(x) == Nmeas)

tau   = (0:Nfine)/Nfine       
tau   = tau[1:(length(tau)-1)] 
fmin  = 1
fmax  = 24 
fvec  = seq(from=fmin,to=fmax,length.out=Nfreq)

for (freq in fvec ){
  cvec  = matrix(cos(2*pi*freq*tau),nrow=Nfine)
  svec  = matrix(sin(2*pi*freq*tau),nrow=Nfine)
  
  a11   = cvec*cvec
  a22   = svec*svec
  a12   = cvec*svec
  bvec  = a11+a22
  Amat  = a11%*%t(a11) + a22%*%t(a22) +4*a12%*%t(a12)-a11%*%t(a22) - a22%*%t(a11)
  A12   = Re(expm::sqrtm(Amat))
  if (freq==fmin){
    obj   = 0.5*(Nmeas - CVXR::norm2(A12%*%x))
  }else{
    obj   = rbind(obj,0.5*(t(bvec)%*%x - CVXR::norm2(A12%*%x)))
  }
}

prob         = Problem(Maximize(min_entries(obj)),constraints)
result       = solve(prob,verbose=T,num_iter=1e7)
result$getValue(objet=x)


```