```{r}
library(devtools)
library(ggplot2)
library(patchwork)
library(ggplotify)
load_all('.')

sa_m_col = '#F57600'# matlab simul anneal 
sa_R_col = '#0073e6'# R simul anneal
cvxr_col = '#5BA300'# R cvxr color
unif_col = 'black'

```

# Load data
```{r}
opts       = make_default_opts(prob_size='medium',solver_type='cvxr')
opts$Nfine = 12*24 # 5 minute intervals 
opts$Nmeas = 16 
opts$fmin  = 1
opts$fmax  = 24

ens_size = 100
sa_m       = runif(opts$Nmeas*ens_size) %>% matrix(nrow=ens_size,ncol=opts$Nmeas)
sa_R       = runif(opts$Nmeas*ens_size) %>% matrix(nrow=ens_size,ncol=opts$Nmeas)
cvxr       = runif(opts$Nmeas*1) %>% matrix(nrow=1,ncol=opts$Nmeas)

```

# Distribution of solutions 

```{r}
df=data.frame()

colors=c('direct power'        = '#F57600', # matlab
         'simulated annealing' = '#0073e6', # R
         'convex programming'  = '#5BA300', # R
         'uniform'             = 'black')

sa_m_name = names(colors)[1]
sa_R_name = names(colors)[2]
cvxr_name = names(colors)[3]

opt_name_list = c(sa_m_name,
                  sa_R_name,
                  cvxr_name)

opt_name_factor = factor(opt_name_list,levels=opt_name_list)

ens_size_list = c(ens_size,ens_size,1)
for (jj in 1:3){
  for (ii in 1:ens_size_list[jj]){
    if (jj<3){pos=ii-ens_size/2}else{pos=0}
    df=rbind(df,data.frame(t=runif(opts$Nmeas),batch=pos,optimizer=opt_name_factor[jj]))
  }
}
dfmt=df

#TODO: turn off y label and ticks
p1=df %>% ggplot(aes(x=t,y=batch,color=optimizer))+geom_point()+
  facet_wrap(~optimizer,nrow=3)+
  scale_color_manual(values=colors)+theme(legend.position='bottom')

```


# Histogram of costfun values
```{r}
df1=data.frame(Jx=rnorm(1000,mean=-1,sd=1),optimizer=sa_m_name)
df2=data.frame(Jx=rnorm(1000,mean=1,sd=2),optimizer=sa_R_name)
df3=data.frame(Jx=1.5,optimizer=cvxr_name)
df=rbind(df1,df2,df3)

#TODO: better x label
p2=df[df$optimizer%in% c(sa_m_name,sa_R_name),] %>% 
  ggplot(aes(x=Jx,fill=optimizer))+
  geom_histogram(position='identity',alpha=.9)+
  geom_vline(xintercept = 1.5,color=colors[names(colors)==cvxr_name]) +
  scale_fill_manual(values=colors)

get_legend <- function(p) {
   tmp <- ggplot_gtable(ggplot_build(p))
   leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
   legend <- tmp$grobs[[leg]]
   legend
}


```


# Power cross sections
```{r}
library(annmatrix)
#eval_exact_power()

am=annmatrix(matrix(runif(opts$Nmeas*ens_size*2),
                 nrow=2*ens_size,ncol=opts$Nmeas),
             rann=list(
               optimizer=rep(c(sa_m_name,sa_R_name),each=ens_size)))
am$mt='mt'

t_unif = c(0:opts$Nmeas)/opts$Nmeas
t_unif = t_unif[1:(length(t_unif)-1)]
am_unif =as.annmatrix(matrix(t_unif,nrow=1))
am_unif@optimizer=c('uniform')
am_unif$mt='mt'

am_cvxr=as.annmatrix(matrix(runif(opts$Nmeas),nrow=1))
am_cvxr@optimizer=c(cvxr_name)
am_cvxr$mt='mt'

am=rbind(am,am_unif,am_cvxr)
am@optimizer %>% unique()

fmin = opts$fmin
fmax= opts$fmax
Nf    = 2^6
Nacro = 2^6
freqs = seq(from=fmin,to=fmax,length.out=Nf)
acros = seq(from=0,to=2*pi,length.out=Nacro+1)
acros = acros[1:Nacro]

# define cost function 
for (ii in c(1:dim(am)[1])){
  mt=am[ii,]
  Amps=seq(from=1/2,to=4,by=.1)
  pwr=lapply(Amps,function(amp){
    pars  = expand.grid(Amp=amp,freq=freqs,acro=acros)
    worst_power = function(mt){
      min(apply(pars,1,function(x){eval_exact_power(t=mt,param=x)}))
    }
    worst_power(mt)
  }) %>% unlist()
  
  amloc=annmatrix(matrix(pwr,nrow=1),
               cann=list(Amp=Amps),
               rann=list(optimizer=am@''[ii,]))
  if (ii==1){
    Ampam=amloc
  }else{
    Ampam=rbind(Ampam,amloc)
  }
}
```



```{r}
Ampam %>% stack() %>% head()
Ampam@id = c(1:dim(Ampam)[1])
Ampam@amopacity = ifelse(Ampam@optimizer%in%c(sa_R_name,sa_m_name),.1,1 )
#Ampam@am_width = ifelse(Ampam@optimizer%in%c(sa_R_name,sa_m_name),.01,.02)
sizes=c(sa_R_name  = .1,
         sa_m_name = .1,
         cvxr_name = 10,
         'uniform' = 10)
p3=Ampam[Ampam@optimizer %in% c(sa_R_name,sa_m_name),] %>% stack() %>% 
  ggplot(aes(x=Amp,y=value,color=optimizer,group=id))+
  geom_line(alpha=.5,size=.1)+
  scale_color_manual(values=colors)

p3=p3+geom_line(data=stack(Ampam[!(Ampam@optimizer %in% c(sa_R_name,sa_m_name)),]),
             aes(x=Amp,y=value,color=optimizer,group=id),alpha=1,size=2)
```


```{r}
theme_set(theme_bw())
leg=get_legend(p1)

#TODO: higher resolution for panel C, make this option
#TODO: turn off legend title
#TODO: common legend, use same aesthetic throughout legend (i.e. color box)
#TODO: font scaling and image spacing
pcomp=as.ggplot(
  {(p1+(p2/p3))+
      plot_annotation(tag_levels='A') & 
      theme(legend.position='none')})
(pcomp/leg)+plot_layout(heights=c(8,1))
```