
# Setup
```{r}

require(devtools)
require(ggplot2)
require(annmatrix)
require(ggplotify)
require(patchwork)
require(parallel)
require(data.table)
require(stringr)
source('plotConfig.R')
load_all()
theme_set(theme_bw())
fs_glob=9

L1vals = c(0,0.1,0.5)
Nmvals = seq(from=16,to=32,by=4)

pars = expand.grid(regL1=L1vals,Nmeas=Nmvals)
```

```{r}
gset = list(
  Nmeas             = 16,
  Nfreq             = 2^8,
  Nfine             = 288,
  trace_global      = 1,
  report_global     = 1,
  maxit_bfgs        = 100, 
  maxit_sa          = 1e3,
  Amp_global        = 2.5,
  nrep              = 100,
  regL1             = 1
)

freqs_global  = seq(from=1,to=24,length.out=gset$Nfreq)

df = NULL

rlist=c(1:dim(pars)[1]) %>% as.list() %>% mclapply(mc.cores=10,FUN=function(ii){
  x=pars[ii,] 
  Nmeas          = x[['Nmeas']]
  regL1          = x[['regL1']]
  gset$Nmin_2lat = floor(Nmeas/4)
  gset$Nmax_2lat = floor(3*Nmeas/4)
  
  var0_cts_lat_bfgs = list(x0=c(shift2=0.5,
                                scale1=.5,
                                scale2=.5,
                                shift1=0),
    lat1 =NULL,lat2 =NULL) 
  if (meth=='bfgs'){
    ctrl_cts_lat_bfgs = list(costfun_choice='svdpower_2lattice',
      optim_method='L-BFGS-B',
      trace=gset$trace_global,
      REPORT=gset$report_global,
      maxit=gset$maxit_bfgs)
      
    res = wrapper_sweep_lattice(opt_osc_power,
      Nvals    = c(gset$Nmin_2lat:gset$Nmax_2lat),
      Nmeas    = Nmeas,
      cts_flag = T,
      dvar0    = var0_cts_lat_bfgs,
      control  = ctrl_cts_lat_bfgs,
      freqs    = freqs_global,
      Amp      = gset$Amp_global,
      regL1    = regL1)  
  }else if(meth=='sa'){
  ctrl_cts_arb_sa   = list(costfun_choice='svdpower',optim_method='simul_anneal',
              tfun_choice='brownian-torus',tfun_mean=0,tfun_sd=.1,
              trace=gset$trace_global,REPORT=gset$report_global,maxit=gset$maxit_sa) 
      
    res = wrapper_sweep_lattice(opt_osc_power,
      Nvals    = c(gset$Nmin_2lat:gset$Nmax_2lat),
      Nmeas    = Nmeas,
      cts_flag = T,
      dvar0    = var0_cts_lat_sa,
      control  = ctrl_cts_lat_sa,
      freqs    = freqs_global,
      Amp      = gset$Amp_global,
      regL1    = regL1)  
  }
  return(data.frame(time=res$res_best$mtvalue,Nmeas=Nmeas,
                      regL1=regL1,lat1Frac=res$N1_best/Nmeas))
})

for (ii in c(1:length(rlist))){
  df=rbind(df,rlist[[ii]])
}
nrow(df)

df %>% ggplot(aes(x=time,y=1,color=as.factor(lat1Frac)))+
  geom_point()+theme(legend.position = 'none')+
  facet_grid(Nmeas~regL1)
```