# Import data
```{r}
require(devtools)
require(ggplot2)
require(annmatrix)
require(ggplotify)
require(patchwork)
require(parallel)
require(data.table)
require(stringr)
require(dplyr)
require(latex2exp)
load_all()
source('plotConfig.R')

run_import=F
if (run_import){
  source('figs_for_paper/extract_data.R') 
}else{
  df_all = readRDS('figs_for_paper/summary_table/all_methods_summary.RDS')
}
mc_cores=10
```

# Fig 0: motivation
Originally from Fig0_motivation/run_assemble_V2
```{r}
gen_panel_loc=function(mt){
  Nmeas =length(mt)
  mtdf=data.frame(time=mt)
  
  # panel 1 
  t_fine = seq(0,1,.005)
  freqs = c(1,4,9*.99)
  cp_levels = sort(24/freqs) %>% rev()
  cp_labels = round(cp_levels,2) %>%  {paste0(.,' hr')}
  phi_plt1=pi/2
  
  df = freqs %>% lapply(function(freq){
   data.frame(expr=cos(2*pi*freq*t_fine - phi_plt1),freq=freq,time=t_fine)
  }) %>% rbindlist() %>% data.frame()
  
  df_noise = freqs %>% lapply(function(freq){
   data.frame(expr=cos(2*pi*freq*mt - phi_plt1)+rnorm(length(mt)),
              freq=freq,time=mt)
  }) %>% rbindlist() %>% data.frame()
  df$circ_per=24/df$freq
  df$circ_per = factor(df$circ_per,cp_levels,cp_labels)
  df_noise$circ_per=24/df_noise$freq
  df_noise$circ_per = factor(df_noise$circ_per,cp_levels,cp_labels)
  p1=ggplot()+geom_line(data=df,aes(x=24*time,y=expr,group=circ_per,color=circ_per))+
    scale_color_manual(values = freq_colors)+
    geom_point(data=df_noise,aes(x=24*time,y=expr,color=circ_per),size=.5)+
    facet_wrap(~circ_per,ncol=3)+
    labs(y='simulated expression',x='measurement time (hr)')+
    scale_x_continuous(limits=c(0,24),breaks = 4*c(0:6))
 
  # panel 2 
  Nmc=1e2
  monteCarloPval <-function(tvec,Amp,freq,acro){
    Ydat = replicate(Nmc,{Amp*cos(2*pi*freq*tvec -acro) + rnorm(length(tvec))}) %>% t
    return(rowCosinor(Ydat,tvec,per=1/freq) %>% {.$pvalue} )
  }
  acrovec=seq(from=0,to=2*pi,.05)
  pars=expand.grid(freq=freqs,acro=acrovec)
  
  #TODO: better way of doing this
  df=c(1:dim(pars)[1]) %>% lapply(function(ind){
    x=pars[ind,]
    freq=as.numeric(x['freq'])
    acro=as.numeric(x['acro'])
    return(data.frame(freq=freq,acro=acro,
                      pvalue=monteCarloPval(mt,Amp,freq,acro)))
  }) %>% rbindlist() %>% data.frame()
  
  
  df$circ_per=24/df$freq
  df$circ_per = factor(df$circ_per,cp_levels,cp_labels)
  
  p2=df %>% ggplot(aes(x=acro,y=-log10(pvalue),color=circ_per))+
    geom_point(size=.5,alpha=.2)+
    facet_wrap(~circ_per,nrow=3)+
    geom_hline(aes(yintercept =-log10(.05),linetype='p=0.05'),color='black')+
    scale_x_continuous(limits=c(0,2*pi),breaks =rad_brk,labels = rad_lab)+
    labs(x='acrophase (rad)',y='-log(pvalue)',linetype=element_blank())+
    scale_color_manual(values=freq_colors)+scale_linetype_manual(values=c('dashed'))+guides(color='none')+
    ylim(c(0,10))

  Fig=p1+p2 + plot_layout(guides='collect') & theme(
     strip.background=element_blank(),
     text=element_text(size=9),
     plot.margin=margin(0,0,0,0),
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank(),
     axis.text.x = element_text(vjust = 0.25)
  )& labs(color='period')
 return(Fig) 
}


cols=viridisLite::viridisMap(3,begin=.3,end=.7,option='magma')
freq_colors=c(rgb(cols[1,c(1:3)]),rgb(cols[2,c(1:3)]),rgb(cols[3,c(1:3)]))
Nmeas = 18
mt_unif = c(1:Nmeas)/Nmeas-1/Nmeas

Amp = 3
Na  = 14
Nb  = Nmeas-Na
mta = c(1:Na)/Na-1/Na
mtb = c(1:Nb)/Nb-1/Nb
mt_alt  =c(mta/2,.5 + mtb/2) 

F1=gen_panel_loc(mt_unif)
F2=gen_panel_loc(mt_alt)
F1=as.ggplot(F1&theme(legend.position = 'none'))
F2=as.ggplot(F2&theme(legend.position = 'bottom'))

Fig = F1/F2 + plot_annotation(tag_levels ='A')+plot_layout(guides='collect',heights = c(5,6.5))
ggsave(paste0(overleaf_plot_directory,'motivation_fig_v2.png'),Fig,width=6,height=6,device='png',dpi=600)

```

# Fig 1: power sweep 
```{r}
Nfreq=2^10
freqs=seq(1,24,length.out=Nfreq)
Nmv = c(16,32)
flist = NULL
p3Amp=1

# load in solutions
for (Nm in Nmv){
  f1 = paste0('transfer_fold/gurobi_raw/sol_gur_free_Nmeas_',Nm,'.RDS')
#  f2 = paste0('transfer_fold/gurobi_spt/sol_gur_drts_6_Nmeas_',Nm,'.RDS')
  f3 = paste0('transfer_fold/gurobi_spt2/sol_gur_drts_12_Nmeas_',Nm,'.RDS')
  f4 = paste0('transfer_fold/gurobi_spt3/sol_gur_drts_18_Nmeas_',Nm,'.RDS')
  flist=c(f1,f3,f4,flist) 
}
flist
sol_factor_levels = c('uniform','pCHORD 2hr','pCHORD 3hr',
                                 'pCHORD free')
```

```{r}
mtdf=NULL
tau = c(1:144)/144 -1/144
for (ff in flist){
  dfloc=readRDS(ff)
  Nfine=length(dfloc$x)-1
  if (Nfine ==144){
    mt = tau[dfloc$x[1:Nfine]>.9]
    mtloc = data.frame(time=mt,solver=ff,Nmeas=length(mt))
    mtdf=rbind(mtdf,mtloc)
  }
}
mtdf %>% head()
mtdf[grepl('sol_gur_free',mtdf$solver),]$solver='pCHORD free'
#mtdf[grepl('drts_6',mtdf$solver),]$solver='pCHORD 1hr'
mtdf[grepl('drts_12',mtdf$solver),]$solver='pCHORD 2hr'
mtdf[grepl('drts_18',mtdf$solver),]$solver='pCHORD 3hr'
```

```{r}
for (Nmeas in Nmv){
  mt_unif = c(1:Nmeas)/Nmeas - 1/Nmeas
  mtloc=data.frame(time=mt_unif,solver='uniform',Nmeas=Nmeas)
  mtdf=rbind(mtdf,mtloc)
}

mtdf %>% head()
mtdf$solver=factor(mtdf$solver,sol_factor_levels)
```

## Plot solutions
```{r}
p1=mtdf %>% ggplot(aes(x=24*time,y=solver,color=solver))+
  geom_point(size=.5)+facet_wrap(~Nmeas,ncol=2)+
  scale_y_discrete(limits=rev)+
  scale_x_continuous(limits=c(0,24),breaks = 4*c(0:6))+labs(x='time (hr)')
p1

```

## Plot power curves
```{r}
solvers=mtdf$solver %>% unique()
Amps=seq(0,3,length.out=50)
pars=expand.grid(solver=solvers,Nmeas=Nmv,Amp=Amps)

pwrdf = c(1:dim(pars)[1]) %>% mclapply(function(ii){
  x = pars[ii,]
  solver = x[['solver']]
  Nmeas  = as.numeric(x[['Nmeas']])
  Amp    = as.numeric(x[['Amp']])
 
  mt = mtdf[mtdf$solver==solver & mtdf$Nmeas==Nmeas,]$time%>% as.numeric()
  power=costfun_svdpower(mt,freqs,Amp,cfuntype = 'power')
  return(data.frame(Amp=Amp,power=power,solver=solver,Nmeas=Nmeas))
}) %>% rbindlist() %>% data.frame()

pwrdf$solver=factor(pwrdf$solver,sol_factor_levels)
```


```{r}
p2=pwrdf %>% ggplot(aes(x=Amp,y=power,group=solver,color=solver))+
  geom_line(show.legend=F)+
  geom_vline(aes(xintercept = p3Amp,linetype='Amp=1'),show.legend=F)+
  scale_linetype_manual(values='dashed')+
  facet_wrap(~Nmeas,ncol=3)+labs(x='amplitude',y='min power')
p2

```


## Freq phase power plot
```{r}
Amps = c(1,1.5)
Nfreq_plt=2^7
Nacro=2^5+1
acros=seq(0,2*pi,length.out=Nacro)
acros=acros[1:(length(acros)-1)]
freqs_plt = seq(1,26,length.out=Nfreq_plt)

pars=expand.grid(Amp=Amps,solver=solvers,Nmeas=Nmv,acro=acros,freq=freqs_plt)


#TODO: write this so that it doesnt have to search dataframe
pwr2df = c(1:dim(pars)[1]) %>% mclapply(function(ii){
  x = pars[ii,]
  solver = x[['solver']]
  Nmeas  = as.numeric(x[['Nmeas']])
  acro   = as.numeric(x[['acro']])
  freq   = as.numeric(x[['freq']])
  Amp    = as.numeric(x[['Amp']]) 
  param =list(Amp=Amp,freq=freq,acro=acro) 
  
  mt = mtdf[mtdf$solver==solver & mtdf$Nmeas==Nmeas,]$time%>% as.numeric()
  power=eval_exact_power(mt,param)
  return(data.frame(acro=acro,freq=freq,power=power,solver=solver,Nmeas=Nmeas,Amp=Amp))
}) %>% rbindlist() %>% data.frame()

head(pwr2df)

```

```{r}
pwr2df$solver=factor(pwr2df$solver,sol_factor_levels)
p3=pwr2df[pwr2df$Amp==p3Amp,] %>% ggplot(aes(x=freq,y=acro,fill=power))+geom_raster()+
  facet_grid(solver~Nmeas)+
  scale_y_continuous(limits=c(0,2*pi),breaks =rad_brk[c(1,3,5)],labels = rad_lab[c(1,3,5)])+
  scale_fill_viridis_c(limits=c(0,1))+
  labs(y='acrophase (rad)',x='frequency (cycles/day)')
```

```{r}
Fig=p1/p2/p3 + plot_layout(guides='collect',heights = c(.23,.3,1.5)) + plot_annotation(tag_levels='A')  &
   theme(
     legend.position = 'bottom',
     legend.box = 'vertical',
     strip.background=element_blank(),
     text=element_text(size=9),
     plot.margin=margin(0,0,0,0),
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank(),
     axis.text.x = element_text(vjust = 0.25)
  ) 
ggsave(paste0(overleaf_plot_directory,'cvxrVaug_powerFDR.png'),Fig,width=6,height=7,device='png',dpi=600)


```

# Fig 2: param accuracy 
```{r}
Nmeas = 16 
Nmc   = 5e2
Amin  = log2(1)
Amax  = log2(5)
fmin  = 1
fmax  = 24

Nfreq_test = 2^6
fmin_test=fmin
fmax_test=fmax*.99 #TODO fix detuning

names=unique(mtdf$solver)
mdf=names %>% lapply(function(solver){
  mt = mtdf[mtdf$solver==solver & mtdf$Nmeas==Nmeas,]$time
  # make pars
  Amps    = 2^runif(Nmc,Amin,Amax) %>% matrix(nrow=Nmc)
  freqs   = runif(Nmc,fmin,fmax) %>% matrix(nrow=Nmc)
  acros   = runif(Nmc,0,2*pi) %>% matrix(nrow=Nmc)
  
  # make data
  acromat = replicate(Nmeas,{acros}) %>% matrix(ncol=Nmeas)
  Ampmat  = replicate(Nmeas,{Amps}) %>% matrix(ncol=Nmeas)
  X       = Ampmat*cos(2*pi*freqs%*%t(mt) - acromat) + rnorm(Nmeas*Nmc) %>% matrix(nrow=Nmc)
 
  test_freqs = seq(from=fmin_test,to=fmax_test,length.out=Nfreq_test) 
  
  Lfit = test_freqs %>% lapply(function(freq){
    cbind(rowCosinor(X,zts=mt,per=1/freq),data.frame(freq=freq))
  }) 
  
  ests = c(1:Nmc) %>% mclapply(mc.cores=mc_cores,function(jj){
    fits = Lfit %>% lapply(function(df){df[jj,]}) %>% rbindlist()
    return(cbind(data.frame(qval=p.adjust(fits$pvalue,method='fdr')),
                 data.frame(fits[which.min(fits$pvalue),])))
  })
  
  res=ests %>% rbindlist()
  names(res) = names(res) %>% sapply(function(x){paste0(x,'_est')})
 
  cbind(res,data.frame(Amp_true=Amps,freq_true=freqs,acro_true=acros,method=solver)) 
}) %>% rbindlist()

head(mdf)

mdf$method=factor(mdf$method,sol_factor_levels)
```


```{r}
al_glob=.5
sz_glob=.5
p1=mdf %>% ggplot(aes(x=Amp_true,y=amplitude_est,color=qval_est<.05))+
  geom_point(alpha=al_glob,size=sz_glob) +
  facet_wrap(~method,nrow=1)+
  scale_color_manual(values=c('red','black'))+
  scale_y_continuous(trans='log2')+scale_x_continuous(trans='log2')

p2=mdf %>% ggplot(aes(x=acro_true,y=phase_est,color=qval_est<.05))+
  geom_point(alpha=al_glob,size=sz_glob) + 
  scale_color_manual(values=c('red','black'))+
  facet_wrap(~method,nrow=1)

p3=mdf %>% ggplot(aes(x=freq_true,y=freq_est,color=qval_est<.05))+
  geom_point(alpha=al_glob,size=sz_glob) + 
  scale_color_manual(values=c('red','black'))+
  facet_wrap(~method,nrow=1)
```


```{r}

p1c = p1+
  theme(
    strip.background=element_blank(),
    text=element_text(size=fs_glob),
    legend.position='bottom'
    )+
  labs(
    x='true amplitude',
    y='estimate',
    color='true frequency (1/day)'
  )
p2c = p2+
  theme(
    strip.background=element_blank(),
    text=element_text(size=fs_glob),
    legend.position='bottom'
    )+
  labs(
    x='true acrophase (rad)',
    y='estimate',
    color='true frequency (1/day)'
  )

p3c = p3+
  theme(
    strip.background=element_blank(),
    text=element_text(size=fs_glob),
    legend.position='bottom'
    )+
  labs(
    x='true frequency (1/day)',
    y='estimate',
    color='true frequency (1/day)'
  )
```

```{r}
sc=0
Fig=(p1c/p2c/p3c) + plot_annotation(tag_levels = 'A')+plot_layout(guides='collect')&
  theme(legend.position='right',
        legend.title.position = 'left',
        legend.title = element_text(angle=-90),
        plot.margin=margin(-sc,-sc,-sc,-sc)
        )
ggsave(paste0(overleaf_plot_directory,'accuracy_benchmark.png'),Fig,width = 6,height=6,device='png',dpi=100)

```

# Fig 3: Lomb-Scargle 
```{r}


```

# Fig 4: Distribution of optimal designs 
```{r}


```