# Setup
```{r}
library(dplyr)
library(patchwork)
library(ggplot2)
library(ggplotify)
library(data.table)
library(pracma)
source('plotConfig.R')
getTvec = function(tau,tvec1,tvec2,design_method){
  if (strcmp(design_method,'poly')){
    tvec = c((tvec1+c(tau))%%1,tvec2)
  }else if(strcmp(design_method,'seq')){
    svec1 = tvec1*c(tau)
    svec2 = tvec2*(1-c(tau))
    tvec  = c(svec1,c(tau)+svec2) 
  }
  return(tvec)
}
detFvec = function(tvec,fvec){
  Cmat = cos(2*pi*outer(fvec,tvec))
  Smat = sin(2*pi*outer(fvec,tvec))
  J    = rowSums(Cmat*Cmat)*rowSums(Smat*Smat)-rowSums(Cmat*Smat)^2
  return(J)
}
vis_colors <- c("Alternative" = "blue", 'Uniform'='black')
```

```{r}
Nfreq = 1e3
Ntau  = 2e3
fmin  = 1
fmax  = 24
fvec  = seq(from=fmin,to=fmax,length.out=Nfreq)

# want to vary N, design_method
Nvals = c(12,24,48)
dmeth = c('seq','poly')

stngs = expand.grid(N=Nvals,dm=dmeth)

#df = stngs %>% apply(1,function(x){
#  N     = x[['N']] %>% as.numeric() 
#  t     = (0:N)/N
#  
#  N1    = 3*N/4 
#  N2    = N-N1
#  tvec1 = (0:N1)/N1 
#  tvec2 = (0:N2)/N2 
#  tvec1 = tvec1[1:(length(tvec1)-1)]
#  tvec2 = tvec2[1:(length(tvec2)-1)]
#  
#  design_method = x[['dm']]
#  taumax = ifelse(strcmp(design_method,'seq'),1,min(diff(tvec2)))
#  taus          = seq(from=0,to=taumax,length.out=Ntau)
#  ys            = sapply(taus,function(tau){
#    min(detFvec(getTvec(tau,tvec1,tvec2,design_method),fvec))
#  })
#  return(data.frame(tau=taus/taumax,cfun=ys/N,
#           design_method=x[['dm']],
#           Nmeas = x[['N']]))
#}) %>% rbindlist()
#df %>% ggplot(aes(x=tau,y=cfun,group=design_method,color=design_method))+
#  geom_line()+facet_wrap(~Nmeas)
```
# Main fig

## Iterate over N1 and plot designs
```{r}
Nmeasvec = c(12,16,24)
#Nmeasvec = c(16,20)

df_PDES = Nmeasvec %>% as.list() %>% lapply(function(NN){
  N = NN
    
  Nfreq = 1e3
  Ntau  = 5e2
  fmin  = 1
  fmax  = 24
  fvec  = seq(from=fmin,to=fmax,length.out=Nfreq)
  
  dmeth = c('seq','poly')
  
  stngs = expand.grid(N1=seq(from=4,to=N/2,by=1),desm=dmeth)
  
  
  df = stngs %>% apply(1,function(x){
    N1 = as.numeric(x[['N1']])
    design_method = as.character(x[['desm']])
  
    N2    = N-N1
    tvec1 = (0:N1)/N1 
    tvec2 = (0:N2)/N2 
    tvec1 = tvec1[1:(length(tvec1)-1)]
    tvec2 = tvec2[1:(length(tvec2)-1)]
    
    taumax = ifelse(strcmp(design_method,'seq'),1,min(diff(tvec2)))
    taus   = seq(from=0,to=taumax,by=Ntau) 
    ys     = sapply(taus,function(tau){
      min(detFvec(getTvec(tau,tvec1,tvec2,design_method),fvec))
    })
   
    tau_init = taus[which.max(ys)]
    
    res=optim(par=tau_init,
          fn =function(tau){
            -min(detFvec(getTvec(tau,tvec1,tvec2,design_method),fvec))},
          lower=0,upper=taumax,method='L-BFGS-B',
          control=list(trace=0))
    
    return(c(x,best_tau = res$par, best_val = -res$value) %>% t() %>% data.frame())
  }) %>% rbindlist()
  
  df_seq = df[df$desm=='seq',]
  tauseq = as.numeric(df[which.max(df_seq$best_val),c('best_tau')])
  N1seq  = as.numeric(df[which.max(df_seq$best_val),c('N1')])
  tau   = tauseq
  N1    = N1seq 
  N2    = N-N1
  tvec1 = (0:N1)/N1 
  tvec2 = (0:N2)/N2 
  tvec1 = tvec1[1:(length(tvec1)-1)]
  tvec2 = tvec2[1:(length(tvec2)-1)]
  tvec_seq = getTvec(tau,tvec1,tvec2,'seq')
  
  df_poly = df[df$desm=='poly',]
  taupoly = as.numeric(df[which.max(df_poly$best_val),c('best_tau')])
  N1poly  = as.numeric(df[which.max(df_poly$best_val),c('N1')])
  tau   = taupoly
  N1    = N1poly 
  N2    = N-N1
  tvec1 = (0:N1)/N1 
  tvec2 = (0:N2)/N2 
  tvec1 = tvec1[1:(length(tvec1)-1)]
  tvec2 = tvec2[1:(length(tvec2)-1)]
  tvec_poly = getTvec(tau,tvec1,tvec2,'poly')
  
  t=(0:N)/N
  t=t[1:(length(t)-1)]
  t0=t
  
  return(rbind(data.frame(Nmeas=N,time=t0,sched='unif'),
    data.frame(Nmeas=N,time=tvec_poly,sched='poly'),
    data.frame(Nmeas=N,time=tvec_seq,sched='seq')))
}) %>% rbindlist()



PDES = df_PDES %>% ggplot(aes(x=time,y=sched,color=sched))+
  geom_point()+theme(legend.position = "none")+facet_wrap(~Nmeas,ncol=length(Nmeasvec),strip.position = 'top')
```

## Plot cost function for each design
```{r}

df_PDET = expand.grid(Nmeasloc=Nmeasvec,sc_type=c('unif','seq','poly')) %>% 
  apply(1,function(x){
    sc_type  = x[['sc_type']]
    Nmeasloc = x[['Nmeasloc']]
    
    tvec = df_PDES %>% filter(sched==sc_type,Nmeas==Nmeasloc) %>% {.$time} 
    
    return(data.frame(freq=fvec,detRedFIM=detFvec(tvec,fvec),sched=sc_type,Nmeas=Nmeasloc))
  }) %>% rbindlist()

PDET = df_PDET %>% ggplot(aes(x=freq,y=detRedFIM,group=sched,color=sched))+geom_line()+facet_wrap(~Nmeas,ncol=length(Nmeasvec),scales='free_y')
```

## Plot power for each design
```{r}
source('utils/powerUtils.R')
param=list(Amp=1,
           acro=0,
           freq=1)
amps= seq(from=1.5,to=3,by=.5)
fvec_plt = seq(from=fmin,to=fmax,by=.1)
df_PPWR = pars = expand.grid(amp=amps,
                   freq=fvec_plt,
                   Nmeasloc=Nmeasvec,
                   sc_type=c('unif','seq','poly')) %>% 
  apply(1,function(x){
    param$Amp  = as.numeric(x[['amp']])
    param$freq = as.numeric(x[['freq']])
    sc_type    = x[['sc_type']]
    Nmeasloc   = x[['Nmeasloc']]
    
    tvec = df_PDES %>% filter(sched==sc_type,Nmeas==Nmeasloc) %>% {.$time} 
    return(c(x,pwr=getMinPower(tvec,param) ) %>% t() %>% data.frame())
  }) %>% rbindlist()

df_PPWR$amp = as.numeric(df_PPWR$amp)                     
df_PPWR$pwr = as.numeric(df_PPWR$pwr)
df_PPWR$freq = as.numeric(df_PPWR$freq)
PPWR = df_PPWR %>% ggplot(aes(x=freq,y=pwr,group=amp,color=amp))+geom_line()+facet_grid(sc_type~Nmeasloc,switch = 'y')+scale_color_viridis_c()
```


```{r}
PDES2 = PDES+guides(color=F)
{PDES2  / PDET / PPWR}+plot_annotation(tag_levels='A')+plot_layout(heights= c(1,1,3),guides='collect') &theme(legend.position = 'right',
        legend.direction = 'vertical',
        legend.box = 'vertical')
ggsave(paste0(overleaf_plot_directory,"fig_reduced_design_space.pdf"), width = 7, height =8)

```


# Frequency distribution 

```{r}
library(MetaCycle)

Nrep = 1e3
sc_type  = 'seq'
Nmeasloc = 16 
tvec = df_PDES %>% filter(sched==sc_type,Nmeas==Nmeasloc) %>% {.$time} 

# simulate data
runif(1,fmin,fmax)

simdat = replicate(Nrep,
          {freq=runif(1,fmin,fmax)
          acro = 2*pi*runif(1)
          return(c(freq,acro,1.5*cos(2*pi*tvec*freq-acro)+rnorm(length(tvec))))}) %>% t() 
simdat_nopar = simdat[,3:(length(tvec)+2)] 

simdat_nopar %>% write.csv('temp.csv',row.names = T)

# estimate period 
mout = meta2d('temp.csv',filestyle = 'csv',
       timepoints=tvec,
       cycMethod = 'LS',
       minper=1/24,maxper=1.5,
       outputFile = F,adjustPhase = 'predictedPer') 

pdf = data.frame(freq=simdat[,1],acro=simdat[,2],
           freq_est = 1/mout$LS$Period,
           acro_est_LS =mout$meta$LS_adjphase) 

source('utils/rowCosinor.R')
acro_est = replicate(Nrep,{NaN})
for (ii in seq(1,Nrep)){
  acro_est[ii] = rowCosinor(t(simdat_nopar[ii,]),zts=tvec,per=1/pdf$freq_est[ii]) %>% {.$acrophase*pdf$freq_est[ii]*2*pi}
}
pdf$acro_est = acro_est

p1 = pdf %>% ggplot(aes(x=freq,y=freq_est))+geom_point()
p2 = pdf %>% ggplot(aes(x=acro,y=acro_est))+geom_point()
p3 = pdf %>% ggplot(aes(x=freq_est))+geom_histogram()
(p1|p2)/p3

```




  