```{r setup}
library(reticulate)

# only run first time


#virtualenv_create('oscDetectPaper') 
#use_virtualenv('oscDetectPaper',required = T)

#conda_create('oscDetectPaper')
use_condaenv('oscDetectPaper',required=T)
py_config()
```

```{r}

# for open-source MIQP, need to use conda to install so that you get SCIPOPTSUITE too

conda_install(envname='oscDetectPaper',channel = 'conda-forge',packages = 'pyscipopt')

conda_install('scipy',envname = 'oscDetectPaper')
conda_install('cvxpy==1.3.1',envname = 'oscDetectPaper') # using newest version throws error
conda_install('dsp-cvxpy',envname = 'oscDetectPaper')
py_config()

# currently unused
#py_install('pyscipopt',envname = 'oscDetectPaper',method='conda') 
#py_install('gurobipy',envname = 'oscDetectPaper') # for MIQP
```


Test of dsp cand cvxpy
```{python}
import dsp
import cvxpy as cp
import numpy as np
import pyscipopt 

x = cp.Variable(2)
y = cp.Variable(2)
C = np.array([[1, 2], [3, 1]])

f = dsp.inner(x, C @ y)
obj = dsp.MinimizeMaximize(f)

constraints = [x >= 0, cp.sum(x) == 1, y >= 0, cp.sum(y) == 1]
prob = dsp.SaddlePointProblem(obj, constraints)
prob.solve()  # solves the problem

prob.value  # 1.6666666666666667
x.value  # array([0.66666667, 0.33333333])
y.value  # array([0.33333333, 0.66666667])
```


```{python}
Nfine = int(5)
Nfreq = int(4)
x     = cp.Variable(Nfine,integer=True)
y     = cp.Variable(Nfreq,integer=True)

A1     = np.random.rand(Nfine,Nfine)
b      = np.random.rand(Nfine)
A2     = np.random.rand(Nfine,Nfine)
obj    = cp.Minimize(cp.sum_squares( A1 @ x - b))

prob   = cp.Problem(obj)
prob.solve()
#prob.status
#print(x.value)
```


```{python}
from pyscipopt import Model
```