# Using fine frequency grid

```{r}
library(ggplot2)
source('plotConfig.R')
source('utils/powerUtils.R')
source('utils/rowCosinor.R')
source('utils/freqUncertaintyUtils.R')
library(dplyr)
library(annmatrix)
library(patchwork)
library(ggplot2)
library(ggplotify)
library(data.table)
library(pracma)
library(optimr)

vis_colors <- c("Alternative" = "blue", 'Uniform'='black')
N   = 12

t     = (0:N)/N
tunif = t[1:(length(t)-1)]


N1 = 5
N2=N-N1
tvec1 = (0:N1)/N1 
tvec2 = (0:N2)/N2 
tvec1 = tvec1[1:(length(tvec1)-1)]
tvec2 = tvec2[1:(length(tvec2)-1)]
timepar=list(tvec1=tvec1,tvec2=tvec2,
             N1=N1,N2=N2,
             N=N1+N2,
             design_method='poly') 

fmin      = 1 
fmax      = 12
df        = .05
FTwindow=list(fmin=fmin,fmax=fmax,df=df,wmeth='freq')
```


```{r}
evaluate_det_on_FTwindow = function(tau,tpar,FTwindow){
# returns determinant of reduced Fisher information matrix evaluated on either
# a frequency or period window depending on the value of FTwindow$wmeth
  tvec = NaN # construct measurement time vector
  if (strcmp(tpar$design_method,'poly')){
    tvec = c((tpar$tvec1+c(tau))%%1,tpar$tvec2)
  }else if(strcmp(tpar$design_method,'seq')){
    svec1 = tpar$tvec1*c(tau)
    svec2 = tpar$tvec2*(1-c(tau))
    tvec  = c(svec1,c(tau)+svec2) 
  }
  
  res = NaN 
  fts = NaN # discretise freq or period window and evaluate det of reduced FIM
  if (strcmp(FTwindow$wmeth,'freq')){ 
    fts = seq(from=FTwindow$fmin,to=FTwindow$fmax,length.out=FTwindow$Nf) 
    res = fts %>% sapply(function(x){
     (t(cos(2*pi*x*tvec))%*%cos(2*pi*x*tvec))*(t(sin(2*pi*x*tvec))%*%sin(2*pi*x*tvec))-
       ( t(cos(2*pi*x*tvec))%*%sin(2*pi*x*tvec))^2
    }) 
  }else if(strcmp(FTwindow$wmeth,'period')){
    fts = seq(from=FTwindow$permin,to=FTwindow$permax,length.out=FTwindow$Nper) 
    res = fts %>% sapply(function(x){
     (t(cos(2*pi*tvec/x))%*%cos(2*pi*tvec/x))*(t(sin(2*pi*tvec/x))%*%sin(2*pi*tvec/x))-
       ( t(cos(2*pi*tvec/x))%*%sin(2*pi*tvec/x))^2
    }) 
  }
  return(res) 
}

Jfun = function(tau,tpar,FTwindow){
  min(evaluate_det_on_FTwindow(tau,tpar,FTwindow))
}

```


```{r}
N   = 12  # number of measurements

N1 = 5    # partition measurement times
N2=N-N1
tvec1 = (0:N1)/N1 
tvec2 = (0:N2)/N2 
tvec1 = tvec1[1:(length(tvec1)-1)]
tvec2 = tvec2[1:(length(tvec2)-1)]
timepar=list(tvec1=tvec1,tvec2=tvec2,
             N1=N1,N2=N2,
             N=N1+N2,
             design_method='poly') 


fmin      = 1 #  discretize frequency domain
fmax      = 24
Nf        = 5e3
FTwindow=list(fmin=fmin,
              fmax=fmax,
              Nf=Nf,
              permin =1/fmax,
              permax =1/fmin,
              Nper=Nf,
              wmeth='freq')

Ntau=10   # how many multistarts to do in tau param
taumax = ifelse(strcmp(timepar$design_method,'poly'),
                max(diff(timepar$tvec2)),
                1)
taus = seq(from=0,to=taumax,length.out=Ntau) 




df=taus %>% sapply(function(tau_init){
  res= optim(par     = tau_init,
             fn      = function(tau){-Jfun(tau,timepar,FTwindow)},
             lower   = 0,upper=taumax,
             method  = 'L-BFGS-B',
             control = list(trace=0))
    return(res %>% unlist() %>% t() %>%  data.frame())
  }
  ) %>% t() %>% data.frame() 
df$par = df$par %>% as.numeric()
df$value = df$value %>%  as.numeric()

df$value %>% min()
```
















