
### Degeneracy heatmap
```{r}
get_exact_reg = function(tau,fmin,fmax){
  dtau_mat          = outer(tau,tau,'-')
  tau_prod_mat      = outer(tau,tau,'*')
  ncp_reg_mat       = ((sin(4*pi*fmax*dtau_mat) - sin(4*pi*fmin*dtau_mat))*(4*tau_prod_mat*pi^2 + 1))/(4*dtau_mat)
  diag(ncp_reg_mat) = pi*(4*pi^2*tau^2 + 1)*(fmax - fmin) 
  return(sum(sum(ncp_reg_mat)))
}

# compute power with/without regularization
eval_reg_cfun = function(mt,freqs,w_reg){
  # worst-case non-centrality
  ncp = freqs %>% sapply(function(freq){
    getReducedFIM(mt,list(freq=freq)) %>% 
    {getMinEig(.,is_symmetric=T)} 
    })%>% min()
  # for regularization term
  fmin = min(freqs)
  fmax = max(freqs)
  # result
  return(ncp-w_reg*get_exact_reg(mt,fmin,fmax))
}
```

```{r}
nt      = 60*2
Nfreq   = 2^7
Nm      = 24 
fmin    = 1 
fmaxs   = c(6,12,24)
mt_unif = c(1:Nm)/Nm - 1/Nm

ta_vals = seq(0,.5,length.out=nt)
tb_vals = seq(0,.5,length.out=nt)
pars    = expand.grid(ta=ta_vals,tb=tb_vals,fmax=fmaxs,wreg=c(0,1))

pars    = pars[pars$ta < pars$tb,]
pars    = pars[!(pars$ta %in% mt_unif),]
pars    = pars[!(pars$tb %in% mt_unif),]

pars$power = c(1:dim(pars)[1]) %>% mclapply(mc.cores=mc_cores,function(ii){
  x     = pars[ii,]
  ta    = x$ta %>% as.numeric()
  tb    = x$tb %>% as.numeric()
  fmax  = x$fmax %>% as.numeric()
  wreg  = x$wreg %>% as.numeric()
  
  mt    = c(mt_unif,ta,tb) 
  
  freqs = seq(fmin,fmax,length.out=Nfreq)
  
  return(eval_reg_cfun(mt,freqs,wreg))
})

pars$power = as.numeric(pars$power)
pars = pars %>% group_by(wreg,fmax) %>% 
  mutate(gmax = max(abs(power))) %>% ungroup()

pars = pars %>% group_by(wreg,fmax) %>% 
  mutate(power_norm = power/gmax) %>% ungroup()
```

```{r}
theme_set(theme_classic()) 
plt1=pars %>% filter(wreg==0) %>% ggplot(aes(x=ta,y=tb,fill=power_norm))+geom_raster()+scale_fill_viridis_c()+
  facet_wrap(~fmax,nrow=1)

plt2=pars %>% filter(wreg>0) %>% ggplot(aes(x=ta,y=tb,fill=power_norm))+geom_raster()+scale_fill_viridis_c()+
  facet_wrap(~fmax,nrow=1)
plt = plt1/plt2
```

```{r}

plt=plt&theme(text=element_text(size=fsize))

xmin=0
xmax=.5
ymin=0
ymax=.5
plt = plt & scale_x_continuous(limits =c(xmin,xmax),
                               breaks=c(xmin,xmax),
                               labels=round(c(xmin,xmax),2)) 
plt = plt & scale_y_continuous(limits =c(ymin,ymax),
                               breaks=c(ymin,ymax),
                               labels=round(c(ymin,ymax),2)) 

plt = plt & labs(x=TeX('$t_1$'),
                 y=TeX('$t_2$'),
                 fill='objective')

plt=plt&guides(fill=guide_colorbar(title.position='right'))
plt=plt&theme(legend.key.height = unit(plt_height*.06, "in"),
               legend.title = element_text(angle = 90),
               legend.title.align = 0.5,
               legend.direction = "vertical")


plt = plt & theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25))


plt_degen = plt
show_temp_plt(plt,plt_width,plt_height)
```

### Relative performance
Solutions normalized by unconstrained unregularized problem
```{r}
# all solutions that don't have regularization
sols_plt = sols[sols@wreg %in% c(0,1),]
df = sols_plt@''

# calculate figure of merit relative to uniform

df_free =df %>% group_by(Nmeas) %>%
  filter(drts==Inf & wreg==0) %>% 
  mutate(free_ncp = ncp) %>%
  ungroup()

df = left_join(df,df_free[,c('Nmeas','free_ncp')]) 

df = df %>% filter(wreg>0 & drts == Inf)

df = df %>% group_by(Nmeas) %>% 
  mutate(norm_ncp = ncp/free_ncp) %>% 
  ungroup()

plt = df %>% 
  ggplot(aes(x=Nmeas,y=norm_ncp))+
  geom_point(size=1)

xmin = 16
xmax = 48

plt=plt + labs(x=element_text('measurement budget'),
           y=element_text('relative score'),
           color=element_text('constraint'),
           shape=element_text('regularisation'))

plt=plt+theme(text=element_text(size=fsize))

plt = plt + scale_x_continuous(limits =c(xmin,xmax),
                               breaks=seq(xmin,xmax,8),
                               labels=seq(xmin,xmax,8))
plt=plt+guides(color=guide_legend(title.position='right'))


plt=plt+theme(legend.key.height = unit(plt_height*.15, "in"),
               legend.title = element_text(angle = 90),
               legend.title.align = 0.5,
               legend.direction = "vertical")


plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25)
  )

plt_reg_conv = plt

plt_height=2.5
show_temp_plt(plt,plt_width,plt_height)

```

### Raw solutions
```{r}
Nmeas_vals = c(16,20,40)
sloc = sols[sols@wreg==1&sols@drts==Inf,]
splt = sloc %>% stack()
splt = splt[splt$value<Inf,]

plt=splt[splt$Nmeas %in% Nmeas_vals, ] %>% ggplot(aes(x=value,y=0))+geom_point(size=.5)+facet_wrap(~Nmeas,nrow=length(Nmeas_vals))

plt = plt + theme(axis.title.y=element_blank()) 
plt = plt + theme(axis.text.y=element_blank()) 
plt = plt + labs(x=element_text('time (days)'))
plt = plt+scale_x_continuous(limits=c(0,.3),breaks=c(0,.3))
plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25)
  )

plt_width=6
plt_height=3
show_temp_plt(plt,plt_width,plt_height)

psol=plt
```
### Heatmaps

```{r}
Nfreq_plt=2^7
Nacro=2^5+1
acros=seq(0,2*pi,length.out=Nacro)
acros=acros[1:(length(acros)-1)]
freqs_plt = seq(1,24,length.out=Nfreq_plt)

pars=expand.grid(Amp=c(1),Nmeas=Nmeas_vals,acro=acros,freq=freqs_plt)

pwr_vec = c(1:dim(pars)[1]) %>% mclapply(mc.cores=mc_cores,function(ii){
  # unpack
  x      = pars[ii,]
  Nmeas  = as.numeric(x[['Nmeas']])
  acro   = as.numeric(x[['acro']])
  freq   = as.numeric(x[['freq']])
  Amp    = as.numeric(x[['Amp']]) 
  param =list(Amp=Amp,freq=freq,acro=acro) 
  
  mt=as.numeric(sloc[sloc@Nmeas==Nmeas,])
  mt=mt[mt<Inf]
  power=eval_exact_power(mt,param)
  return(power)
})
pars$power = pwr_vec

pars$freq =as.numeric(pars$freq)
pars$acro =as.numeric(pars$acro)
pars$power=as.numeric(pars$power)

plt = pars%>%
  ggplot(aes(x=freq,y=acro,fill=power))+
  geom_raster()+
  facet_wrap(~Nmeas)+
  scale_y_continuous(limits=c(0,2*pi),breaks =rad_brk[c(1,3,5)],labels = rad_lab[c(1,3,5)])+
  scale_fill_viridis_c(limits=c(0,1))+
  labs(y='acrophase (rad)',x='frequency (cycles/day)')

plt=plt+guides(fill=guide_colorbar(title.position='right'))
plt=plt+theme(legend.key.height = unit(.15, "in"),
               legend.title = element_text(angle = 90),
               legend.title.align = 0.5,
               legend.direction = "vertical")

plt = plt + theme(
  strip.background=element_blank(),
  plot.margin = margin(0,0,0,0),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.text.x = element_text(vjust = 0.25)
  )
plt_hmap=plt
plt_hmap
```

### Combine
```{r}
plt_degen    = plt_degen & theme(text=element_text(size=9))
plt_reg_conv = plt_reg_conv & theme(text=element_text(size=9))
psol         = psol& theme(text=element_text(size=9))
plt_hmap     = plt_hmap & theme(text=element_text(size=9))

Fig = (plt_degen/(plt_reg_conv+psol)/plt_hmap )+
  plot_annotation(tag_levels='A')+
  plot_layout(heights = c(1,1,1,1))

plt_width  = 6
plt_height = 7
show_temp_plt(Fig,plt_width,plt_height)
ggsave(paste0('~/research/ms_powerCHORD/figures/','regularization_part2.png'),Fig,width=plt_width,height=plt_height,device='png',dpi=600)
```