test_that("matches old version of fun", {
  source('../../to_be_archived/powerChord_old.R')
  require(dplyr)
  require(devtools)
  Nfine = sample(c(100:200),1) 
  Nmeas = sample(c(1:100),1)
  Nmeasalt = sample(c(1:100),1)
  fmin = 100*runif(1)
  fmax = fmin +100*runif(1)
  drts = sample(c(Inf,6,12,18),1)
  w_reg = runif(1)
  Nfreq = sample(c(2:50),1)
  w_wc = runif(1)
  mod1=powerChord_old(Nmeas,fmin,fmax,drts,w_reg,Nfine,Nfreq,return_model=T)
  mod2=powerChord(Nmeas,fmin,fmax,drts,w_reg,Nfine,Nfreq,return_model=T)
  testthat::expect_equal(mod1,mod2)
})
