# Setup

Install and load required libraries
```{r setup}
rm(list=ls())
require(devtools)
require(ggplot2)
require(annmatrix)
require(ggplotify)
require(patchwork)
require(parallel)
require(data.table)
require(stringr)
load_all()
```

Set up simulation
```{r settings}
mc_cores=10
gset = list(
  Nmeas             = 16,      # measurement budget
  Nfreq             = 2^8,     # number of frequencies to use
  Nfine             = 288,     # corresponds to 5 minute sampling
  trace_global      = 6,       # controls how often to report 
  report_global     = 10,      # how much reporting you want
  maxit_sa          = 1e2,     # max iterations for simulated annealing 
  Amp_global        = NaN,     # amp is irrelevant, not used here
  Nmin_2lat         = 8,       # minimum number of points in lattice
  Nmax_2lat         = 8,       # maximum number of points in lattice
  nrep              = mc_cores # how many simulated annealing trials to run
)
Nmeas=gset$Nmeas
```

# Continuous time simulated annealing 

## Single run
```{r}
freqs=seq(from=1,to=24,length.out=gset$Nfreq)

# simulated annealing options
ctrl_cts_lat_sa = list(
  costfun_choice = 'svdpower_2lattice',
  optim_method = 'simul_anneal',
  tfun_choice  = 'unif-with-bdry',tscale_unif_with_bdry=1,
  trace=gset$trace_global,REPORT=gset$report_global,
  maxit=gset$maxit_sa)

# initial state for simulated annealing 
var0_cts_lat_sa = list(
  x0=c(shift2=1/2/Nmeas,scale1=1,scale2=1,shift1=0),
  lat1 =NULL,
  lat2 =NULL)

# run simulated annealing
resu_cts_lat_sa = wrapper_sweep_lattice(opt_osc_power,
  Nvals    = c(gset$Nmin_2lat:gset$Nmax_2lat),
  Nmeas    = gset$Nmeas,
  cts_flag = T,
  dvar0    = var0_cts_lat_sa,
  control  = ctrl_cts_lat_sa,
  freqs    = freqs,
  Amp      = NaN,
  cfuntype = 'ncp',
  gapPenalty=Nmeas/10)

res=resu_cts_lat_sa
ggplot()+geom_point(aes(x=res$res_best$mtvalue,y=1))+xlim(c(0,1))
```

## Ensemble run
```{r}
resmat=NULL
Lnow = c(1:gset$nrep) %>% as.list() %>%  mclapply(mc.cores=mc_cores,FUN=function(ii){
    var0_cts_lat_sa   = list(x0=c(shift2=1/2/Nmeas,scale1=1,scale2=1,shift1=0),
                             lat1 =NULL,lat2 =NULL)
    resu_cts_lat_sa = wrapper_sweep_lattice(opt_osc_power,
                                Nvals    = c(gset$Nmin_2lat:gset$Nmax_2lat),
                                Nmeas      = gset$Nmeas,
                                cts_flag   = T,
                                dvar0      = var0_cts_lat_sa,
                                control    = ctrl_cts_lat_sa,
                                freqs      = freqs,
                                Amp        = NaN,
                                cfuntype   = 'ncp',
                                gapPenalty = Nmeas/10)
})
resmat=helper_update_amm(resmat,Lnow,gset,tag='cts_lat_sa',wrapped=T,cfunlabel='ncp')

resmat %>% stack() %>% ggplot(aes(x=value,y=ncp))+geom_point()
```

# Discrete problem
## Single run
```{r}
Nfine=gset$Nfine
tau=c(1:Nfine)/Nfine-1/Nfine
ctrl_disc_lat_sa = list(costfun_choice = 'svdpower_2lattice_discrete',
  optim_method   = 'simul_anneal',
  tfun_choice    = 'unif-with-bdry-discrete',tscale= Nfine,
  trace=gset$trace_global,REPORT=gset$report_global,maxit=gset$maxit_sa)

var0_disc_lat_sa = list(
  x0=c(dx1=1,dx2=1,xshift2=Nfine/2),
  N1=NULL,
  N2=NULL)

resu_disc_lat_sa = wrapper_sweep_lattice(opt_osc_power,
  Nvals    = c(gset$Nmin_2lat:gset$Nmax_2lat),
  Nmeas    = Nmeas,
  cts_flag = F,
  dvar0    = var0_disc_lat_sa,
  control  = ctrl_disc_lat_sa,
  freqs    = freqs,
  Amp      = NaN,
  tau      = tau,
  cfuntype= 'ncp',
  gapPenalty=Nmeas/10)
res=resu_disc_lat_sa
ggplot()+geom_point(aes(x=res$res_best$mtvalue,y=1))+xlim(c(0,1))
```

## Ensemble run
```{r}
Lnow = c(1:gset$nrep) %>% as.list() %>%  mclapply(mc.cores=mc_cores,FUN=function(ii){
  resu_disc_lat_sa = wrapper_sweep_lattice(opt_osc_power,
    Nvals    = c(gset$Nmin_2lat:gset$Nmax_2lat),
    Nmeas    = Nmeas,
    cts_flag = F,
    dvar0    = var0_disc_lat_sa,
    control  = ctrl_disc_lat_sa,
    freqs    = freqs,
    Amp      = NaN,
    tau      = tau,
    cfuntype= 'ncp',
    gapPenalty=Nmeas/10)
})
resmat=helper_update_amm(resmat,Lnow,gset,tag='disc_lat_sa',wrapped=T,cfunlabel='ncp')

resmat %>% stack() %>% ggplot(aes(x=value,y=ncp))+geom_point()
```