```{r}
require(devtools)
require(ggplot2)
require(annmatrix)
require(ggplotify)
require(patchwork)
require(parallel)
require(data.table)
require(stringr)
require(CVXR)
source('plotConfig.R')
load_all()
fs_glob=9

```
# Aesthetics
```{r}
p1=readRDS('figs_for_paper/Fig1_aug_vs_cvxr/p1.RDS')
p2=readRDS('figs_for_paper/Fig1_aug_vs_cvxr/p2.RDS')
p3=readRDS('figs_for_paper/Fig1_aug_vs_cvxr/p3.RDS')
p1c=p1+theme(
  legend.position = 'bottom',
  strip.background = element_blank(),
  text=element_text(size=fs_glob)
  )+labs(
    x='time',
    y='non-centrality'
  )
leg1=get_legend(p1c)
p1c=as.ggplot(p1+theme(
  legend.position = 'none',
  strip.background = element_blank(),
  text=element_text(size=fs_glob)
  )+labs(
    x='time',
    y='non-centrality'
  ))


p2c=as.ggplot(p2+
  theme(strip.background=element_blank(),
    text=element_text(size=fs_glob),
    panel.grid=element_blank(),
    panel.border=element_blank()
    )+
  scale_y_continuous(breaks=c(c(1:2),seq(4,16,4),24),trans='log10')+
  labs(fill = 'power',
          y = 'period (hr)',
          x = 'amplitude'))
p3c=p3+
  labs(fill='power',
       y=element_blank())+
  scale_y_continuous(breaks=c(c(1:2),seq(4,16,4),24),trans='log10')+
  theme(
    strip.background=element_blank(),
    text=element_text(size=fs_glob),
    legend.position='bottom',
    legend.key.height= unit(.3,'cm'),
    legend.key.width = unit(.85,'cm'),
    panel.grid=element_blank(),
    panel.border=element_blank()
    )
    
legpower = get_legend(p3c)
p3c=as.ggplot(p3+
  labs(fill='power',
       y=element_blank())+
  scale_y_continuous(breaks=c(c(1:2),seq(4,16,4),24),trans='log10')+
  theme(
    strip.background=element_blank(),
    text=element_text(size=fs_glob),
    legend.position='none',
    panel.grid=element_blank(),
    panel.border=element_blank()
    )
    )


F1top    = (p1c/(p2c|as.ggplot(p3c))) + plot_annotation(tag_levels='A')+plot_layout(heights=c(2,5)) & theme(plot.margin=margin(0,0,0,0))
F1bottom = (as.ggplot(leg1)+as.ggplot(legpower)+plot_layout(widths=c(1,1)))&theme(plot.margin=margin(0,0,0,0))
F1       = (as.ggplot(F1top)/as.ggplot(F1bottom)) + plot_layout(heights=c(20,1))

ggsave(paste0(overleaf_plot_directory,'cvxrVaug_powerFDR.png'),F1,width = 6,height=5,device='png',dpi=600)
```
