```{r}
gc()
library(devtools)
library(gurobi)
library(CVXR)
load_all('.')
```

# Optimal designs - no lattice constraint 

## Simulated annealing
```{r}
# how many batches of simulated annealing 
if (test){
  ens_size = 10 
} else {
  ens_size = 1e2
}

opts=make_default_opts(prob_size='medium',solver_type='simulanneal')

opts$Nfine        = 12*24 # 5 minute intervals 
opts$Nmeas        = 16
opts$fmin         = 1
opts$fmax         = 24
opts$Nfreq        = 2^10 
opts$costfun_type = 'Linfty'
opts$verbose      = F
if (test){
  opts$num_iter     = 150
}else{
  opts$num_iter     = 1e3
}

sa_sols = replicate(ens_size*opts$Nmeas, {NaN})
sa_sols = matrix(sa_sols,nrow=ens_size,ncol=opts$Nmeas)

Aquad=make_quadmats(opts)

for (ii in c(1:ens_size)){
  print(toString(ii))
  xopt         = run_sa_power(Aquad,opts)
  tau          = c(0:opts$Nfine)/opts$Nfine       
  tau          = tau[1:(length(tau)-1)] 
  mt_opt_sa    = tau[xopt$xval==1]
  sa_sols[ii,] = mt_opt_sa
}
saveRDS(sa_sols,'results/sa_sols.RDS')
```

## DCP
```{r}
opts$solver_type = 'cvxr'
opts$Nfreq       = 2^8 #2^7 is cap so far, want to max this before out of memory in pre-solve
opts$verbose     = T
if (test){
  opts$time_limit  = 5 # units of seconds
}else{
  opts$time_limit  = 60*60*24*3 #  3 days 
}

x     = make_variable(opts)
csts  = make_constraints(x,NULL,NULL,opts)
Aquad = make_quadmats(opts)
prob  = make_problem(x,Aquad,csts,opts)
xopt  = run_cvxr_power(prob,opts)

mt_opt_cvxr = tau[xopt$xval==1]

saveRDS(cvxr_sol,'results/cvxr_sol.RDS')
```

```{r}
cvxr_sol
```

