```{r}
require(devtools)
require(annmatrix)
require(stringr)
require(CVXR)
require(gurobi)
require(ggplot2)
require(patchwork)
load_all()

Nfreq        = 47
tlim         = 10  
Nmeas        = 32 
threads_glob = 8 

mtdf=NULL
control=list(
  Nmeas=Nmeas,
  Nfine=144,
  Nfreq=Nfreq,
  fmin=1,
  fmax=24,
  PreSolve=2,
  MIPFocus=2,
  cvxr_verbose=T,
  time_limit=tlim,
  maxit=1e9,
  MIPGapAbs=.001,
  NodefileStart=Inf,
  prob_formulation='hvolume'
  )


#freqs=seq(1,24,length.out=control$Nfreq)
#res=solve_cvxr_spt(control,Threads=threads_glob)
#
#p1=data.frame(time=res$mtvalue) %>% ggplot(aes(x=time,y=1))+geom_point()+xlim(c(0,1))
#p2=data.frame(time=c(1:control$Nfine)/control$Nfine-1/control$Nfine) %>% ggplot(aes(x=time,y=1))+geom_point()+xlim(c(0,1))
#p1/p2

#p2=data.frame(y=res$weight,x=freqs) %>% ggplot(aes(x=x,y=y))+geom_point()
#
#p1/p2

#costfun_svdpower(res$mtvalue,freqs=seq(1,24,length.out=2^10),Amp=2,cfuntype = 'power')
#costfun_svdpower(c(1:Nmeas)/Nmeas,freqs=seq(1,24,length.out=2^10),Amp=1.5,cfuntype = 'power')
```

```{r}
load_all()
Nfreq        = 47
tlim         = 60*5 
Nmeas        = 18 
threads_glob = 8 
control=list(
  Nmeas=Nmeas,
  Nfine=144,
  Nfreq=Nfreq,
  fmin=1,
  fmax=24,
  PreSolve=2,
  MIPFocus=3,
  cvxr_verbose=T,
  time_limit=tlim,
  maxit=1e9,
  MIPGapAbs=.001,
  MIPGap=1e-5,
  NodefileStart=Inf
  )

# construct spt vec
if (control$Nfine==288){
  drts=6*3*2#12
  pads=3*2#11
}else if(control$Nfine==144){
  drts=6*3
  pads=0#5*2
}


Nfine = control$Nfine
tau=c(1:Nfine)/Nfine-1/Nfine

rt_inds=seq(1,Nfine,drts)
cst_times=NULL
for (ii in c(1:length(rt_inds))){
  cst_spt = tau[c(rt_inds[ii]:(rt_inds[ii]+pads))]
  cst_times = c(cst_times,cst_spt)
}
if (control$Nfine==288){
  cst_times*5*12*24
}else if(control$Nfine==144){
  cst_times*10*6*24
}

res=solve_cvxr_spt(control,Threads,use_spt=T,drts,pads)

rbind(data.frame(time=res,type='solution'),data.frame(time=cst_times,type='constraint')) %>% 
  ggplot(aes(x=time,y=type))+geom_point()+xlim(c(0,1))
```