```{r}
require(devtools)
require(ggplot2)
require(annmatrix)
require(ggplotify)
require(patchwork)
require(parallel)
require(data.table)
require(stringr)
require(data.table)
source('plotConfig.R')
load_all()
theme_set(theme_bw())
fs_glob=9
pmaster=NULL

#for (jj in c(1:10)){
#  pars = expand.grid(Amp=c(3),cfun=c('ncp','power'),Nfreq=2^c(6:12),regL1=c(0,1))
#  Nmeas=30
#  mt=runif(Nmeas)
#  pars$fval = c(1:dim(pars)[1]) %>% as.list() %>% mclapply(function(ii){
#    x=pars[ii,]
#    costfun_svdpower(mt=mt,
#                     freqs=seq(from=1,to=24,
#                               length.out=x[['Nfreq']]),
#                     Amp=x[['Amp']],
#                     cfuntype=x[['cfun']])
#  }) %>% unlist()
#  pars$id = jj 
#  pmaster=rbind(pmaster,pars)
#}
#require(dplyr)
#pmaster$mfval=pmaster[,c('fval','Amp','cfun','regL1','id')] %>% group_by(Amp,cfun,regL1,id) %>% mutate(mfval=min(fval)) %>% {.$mfval}
#
#pmaster$nfval = (pmaster$fval-pmaster$mfval)/pmaster$mfval
#pmaster%>% ggplot(aes(x=Nfreq,y=nfval,group=id))+geom_line()+facet_wrap(cfun~regL1,scales='free')+scale_x_continuous(trans='log2')
  
```


# Landscape for different N1,N2 values
```{r}
start=Sys.time()
Nland=30
Nfreq=2^9
Nmeas=16
freqs=seq(from=1,to=24,length.out=Nfreq)
logscale=T
if (logscale){
  scale1=10^{seq(from=-2,to=0,length.out=Nland)}
  scale2=10^{seq(from=-2,to=0,length.out=Nland)}
  shift2=10^{seq(from=-2,to=0,length.out=Nland)}
}else{
  #scale1=seq(from=0.01,to=1,length.out=Nland)
  #scale2=seq(from=0.01,to=1,length.out=Nland)
  #shift2=seq(from=0.01,to=1,length.out=Nland)
}
N1vals=seq(from=floor(Nmeas/4),to=3*floor(Nmeas/4))

pars=expand.grid(scale1=scale1,scale2=scale2,shift2=shift2,
                 N1=N1vals,regL1=c(0,1))


vals=c(1:dim(pars)[1]) %>% as.list() %>% mclapply(mc.cores=10,FUN=function(ii){
  x=pars[ii,]
  scale1=as.numeric(x['scale1'])
  scale2=as.numeric(x['scale2'])
  shift2=as.numeric(x['shift2'])
  regL1 =as.numeric(x['regL1'])
  N1=as.numeric(x['N1'])
  lat1=c(1:N1)/N1-1/N1
  N2=Nmeas-N1
  lat2=c(1:N2)/N2-1/N2
  return(costfun_2lattice_svdpower(shift1=0,shift2=shift2,
                            scale1=scale1,scale2=scale2,
                            lat1=lat1,lat2=lat2,freqs=freqs,
                            Amp=NaN,regL1=regL1,cfuntype='ncp'))
}) %>% unlist()
pars$value=vals

head(pars)
df=NULL
df=c(1:dim(pars)[1]) %>% as.list() %>% mclapply(mc.cores=10,FUN=function(ii){
  x=pars[ii,]
  scale1=as.numeric(x['scale1'])
  scale2=as.numeric(x['scale2'])
  shift2=as.numeric(x['shift2'])
  df1 = data.frame(x=scale1,y=scale2,tag='scale1-scale2',
                   x[!(names(x)%in%c('scale1','scale2','shift2'))])
  df2 = data.frame(x=scale2,y=shift2,tag='scale2-shift2',
                   x[!(names(x)%in%c('scale1','scale2','shift2'))])
  df3 = data.frame(x=shift2,y=scale1,tag='shift2-scale1',
                   x[!(names(x)%in%c('scale1','scale2','shift2'))])
  return(rbind(df1,df2,df3))
}) %>% rbindlist()

df %>% head()
p1=df[df$regL1==0,] %>% ggplot(aes(x=x,y=y,fill=value))+geom_tile()+facet_grid(N1~tag)+scale_fill_viridis_c()+scale_x_continuous(trans='log10')+scale_y_continuous(trans='log10')

p2=df[df$regL1>0,] %>% ggplot(aes(x=x,y=y,fill=value))+geom_tile()+facet_grid(N1~tag)+scale_fill_viridis_c()+scale_x_continuous(trans='log10')+scale_y_continuous(trans='log10')

p1|p2
end=Sys.time()
end-start
```