```{r setup}
require(kableExtra)
require(dplyr)
require(ggplot2)
require(annmatrix)
require(devtools)
require(data.table)
require(parallel)
load_all()
Nfreq = 2^10
freqs = seq(1,24,length.out=Nfreq)
```

# assemble cvxr results
```{r}
sol_dir_cvxr = 'transfer_fold/cvxr_results/'
extract_cvxr = function(fname,sol_name){
  dat       = readRDS(paste0(sol_dir_cvxr,fname))
  xinds     = dat[[1]] 
  Nfine     = length(xinds)
  Nmeas     = sum(xinds)
  tau       = c(1:Nfine)/Nfine -1/Nfine
  mt        = tau[as.logical(xinds)]
  ncp       = costfun_svdpower(mt,freqs,Amp=NaN,cfuntype = 'ncp')
  stat_code = attr(dat$status,'gurobi_status_code')
  stat_desc = attr(dat$status,'gurobi_status_desc')
  data.frame(Nmeas=Nmeas,ncp=ncp,stat_code=stat_code,stat_desc=stat_desc,
             solver=sol_name)
}
extract_cvxr_files = function(fname_list,sol_name){
 return( c(1:length(fname_list)) %>% mclapply(function(ii){
  fname = fname_list[ii]
  extract_cvxr(fname,sol_name)
}) %>% rbindlist() %>% data.frame())
}


# get CVXR solutions
cvxr_files = list.files(sol_dir_cvxr,pattern = 'solns_cvxr*')
res_cvxr   = extract_cvxr_files(cvxr_files,'cvxr') 


# get CVXR supp solutions
cvxr_supp_files_6 = list.files(sol_dir_cvxr,pattern = 'solns_spt_cvxr_drts_6*')
res_supp_6   = extract_cvxr_files(cvxr_supp_files_6,'cvxr_supp_1hr') 

cvxr_supp_files_18 = list.files(sol_dir_cvxr,pattern = 'solns_spt_cvxr_drts_18*')
res_supp_18   = extract_cvxr_files(cvxr_supp_files_18,'cvxr_supp_3hr') 

# get pin2lat solutions
pin2lat_files = list.files(sol_dir_cvxr,pattern='solns_pin2lat')
res_p2l = c(1:length(pin2lat_files)) %>% mclapply(function(ii){
  fname = pin2lat_files[ii]
  dat       = readRDS(paste0(sol_dir_cvxr,fname))
  dat$ncp   = abs(dat$ncp)
  best_rep  = dat[which.max(dat$ncp),]$rep
  mt        = dat[dat$rep==best_rep,] %>% {.$time} %>% unlist()
  Nmeas     = length(mt)
  ncp       = costfun_svdpower(mt,freqs,Amp=NaN,cfuntype = 'ncp')
  stat_code = "NA" 
  stat_desc = NA 
  sol_name  = 'pin2lat'
  return(data.frame(Nmeas=Nmeas,ncp=ncp,stat_code=stat_code,stat_desc=stat_desc,
             solver=sol_name))
}) %>% rbindlist() %>% data.frame()

# get uniform answers
Nm_vals = c(16:48)
res_unif=NULL
for (Nm in Nm_vals){
  mt  = c(1:Nm)/Nm - 1/Nm
  ncp = costfun_svdpower(mt,freqs,Amp=NaN,cfuntype = 'ncp')
  res_unif=rbind(res_unif,data.frame(Nmeas=Nm,ncp=ncp,stat_code='NA',stat_desc=NA,
             solver='uniform'))
}

res = rbind(res_cvxr,res_supp_6,res_supp_18,res_unif,res_p2l)
df  = data.frame(res)

saveRDS(df,file = 'figs_for_paper/summary_table/cvxr_summary.RDS')
```

# assemble raw gurobi results
```{r}
sol_dir_gurobi       =  'transfer_fold/gurobi_raw/'
sol_dir_gurobi_spt   =  'transfer_fold/gurobi_spt/'
sol_dir_gurobi_spt2  =  'transfer_fold/gurobi_spt2/'
sol_dir_gurobi_spt3  =  'transfer_fold/gurobi_spt3/'
gur_files            = list.files(sol_dir_gurobi,pattern='sol_gur_free')
gur_spt_files        = list.files(sol_dir_gurobi_spt,pattern='sol_gur_drts_6')
gur_spt2_files       = list.files(sol_dir_gurobi_spt2,pattern='sol_gur_drts_12')
gur_spt3_files       = list.files(sol_dir_gurobi_spt3,pattern='sol_gur_drts_18')

tau = c(1:Nfine)/Nfine - 1/Nfine
sdir   = sol_dir_gurobi
sol_name = 'cvxr'
gur_thresh = .9 # TODO explain

extract_gurobi  = function(sdir,gur_files,sol_name){
  c(1:length(gur_files)) %>% lapply(function(ii){
    fname  = gur_files[ii]
    gres=readRDS(paste0(sdir,fname))
   
    spart=strsplit(fname,'.RDS')
    Nmeas_expect = as.numeric(substring(spart[[1]],nchar(spart[[1]])-1))
    Nfine = length(gres$x)-1
    
    if (Nfine==144){
      mtloc = tau[gres$x[1:Nfine]>gur_thresh]
    }else{
      stop('inconsistent fine grid')
    }
    Nmeas = length(mtloc)
    Nmeas_good = Nmeas==Nmeas_expect
    
    ncp = costfun_svdpower(mtloc,freqs,Amp=NaN,cfuntype = 'ncp')
    stat_code = gres$status
    stat_desc = NA
    solver    = sol_name
    
    return(data.frame(Nmeas_expect=Nmeas_expect,
      Nmeas=Nmeas,ncp = ncp,
      stat_code=stat_code,stat_desc=stat_desc,
      solver=solver,wrap = 'gurobi_raw',Nmeas_good=Nmeas_good
               ))
  } 
  )%>% rbindlist() %>% data.frame()
}
gdf0=extract_gurobi(sol_dir_gurobi,gur_files,'gurobi_free')
gdf1=extract_gurobi(sol_dir_gurobi_spt,gur_spt_files,'gurobi_spt')
gdf2=extract_gurobi(sol_dir_gurobi_spt2,gur_spt2_files,'gurobi_spt2')
gdf3=extract_gurobi(sol_dir_gurobi_spt3,gur_spt3_files,'gurobi_spt3')

gdf=rbind(gdf0,gdf1,gdf2,gdf3)
gdf$Nmeas_good %>% summary()
```


```{r}
df$wrap = 'cvxr'
df_all=rbind(df,gdf[,names(gdf) %in% names(df)])
df_all$solver %>% unique()

df_all[df_all$solver=='cvxr',]$solver      = 'free' 
df_all[df_all$solver=='gurobi_free',]$solver = 'free' 

df_all[df_all$solver=='cvxr_supp_1hr',]$solver = 'supp_1hr' 
df_all[df_all$solver=='gurobi_spt',]$solver = 'supp_1hr' 

#df_all[df_all$solver=='cvxr_supp_2hr',]$solver = 'supp_2hr' 
df_all[df_all$solver=='gurobi_spt2',]$solver = 'supp_2hr' 

df_all[df_all$solver=='cvxr_supp_3hr',]$solver = 'supp_3hr' 
df_all[df_all$solver=='gurobi_spt3',]$solver = 'supp_3hr' 


```

```{r}
pdf = df_all[df_all$solver %in% c('free','supp_1hr','supp_2hr','supp_3hr'),]

pdf %>% ggplot(aes(x=Nmeas,y=ncp,group=solver,color=solver))+
  geom_point(aes(shape=stat_code),size=2)+facet_wrap(~wrap)
```
