#' Get dominant frequency from regression output
#' 
#' @description
#' Helper function for processing output of [freqsweep_regr()]. For each row,
#' this function selects the frequency with lowest p-value or q-value and returns the
#' corresponding amplitude and acrophase estimates and the p-value or q-value
#' 
#' @param pqvals [annmatrix] of p-values or q-values generated by [matrix_1d_padjust()]
#' @param amps  [annmatrix] of amplitudes, same shape as previous, each row corresponds
#' to a distinct experiment, each column to a distinct frequency
#' @param acros [annmatrix] of acrophases in units of radians
#' 
#' all three inputs to this function can be generated by [freqsweep_regr()]
#' 
#' @return estimated frequency, amplitude, acrophase, and p-value/q-value for each row
#' 
#' @author Turner Silverthorne
#' @export
extract_dominant_freq=function(pqvals,amps,acros){
  amp_est    = replicate(dim(pqvals)[1],{NaN})
  acro_est   = replicate(dim(pqvals)[1],{NaN})
  freq_est   = replicate(dim(pqvals)[1],{NaN})
  min_pq_osc = replicate(dim(pqvals)[1],{NaN})
  
  for (ii in c(1:dim(pqvals)[1])){
    ind            = which.min(pqvals[ii,])
    amp_est[ii]    = amps[ii,ind]
    acro_est[ii]   = acros[ii,ind]
    freq_est[ii]   = pqvals$freq_regr[ind]
    min_pq_osc[ii] = pqvals[ii,ind]
  }
  
  return(list(amp_est    = amp_est,
              acro_est   = acro_est,
              freq_est   = freq_est,
              min_pq_osc = min_pq_osc))
}