#' Get dominant frequency from regression output
#' 
#' @description
#' Helper function for processing output of [freqsweep_regr()]. For each row,
#' this function returns the frequency of lowest q-value and returns the
#' corresponding amplitude acrophase estimates and the q-value
#' 
#' @param qvals annmatrix of qvalues generated by [matrix_1d_padjust()]
#' @param 