#' Independently fit cosinor models at all frequencies in a given range
#' 
#' @description
#' Perform independent harmonic regressions at all frequencies in a given range. 
#' 
#' 
#' @param mt vector of measurement times
#' @param Xdat simulated dataset, for instance generated by [make_simulated_data()]
#' @param fmin lowest frequency to use in harmonic regression
#' @param fmax highest frequency to use in harmonic regression
#' @param return_type controls output of program, do you want only most 
#' significant result or all results?
#'
#' @return a list with [annmatrix::annmatrix()] entries
#' \itemize{
#' \item \code{pvalues} pvalue obtained for harmonic regression at each frequency
#' regression. 
#' \item \code{amps} amplitude estimates for each frequency
#' \item \code{acros} acrophase estimates for each frequency
#' }
#' The individual harmonic regressions are performed using the 
#' [rowCosinor()] function.
#' 
#' @author Turner Silverthorne
#' @export
freqsweep_regr=function(mt,Xdat,fmin,fmax,Nfreq,return_type){
  freqs=seq(from=fmin,to=fmax,length.out=Nfreq)
  pv_am_global  = NULL
  amp_am_global  = NULL
  acro_am_global = NULL
  for (ii in c(1:length(freqs))){
    freq=freqs[[ii]]
    
    rc  = rowCosinor(Xdat,mt,freq)
    pv_am =rc %>% {.$pvalue} %>% 
      matrix(nrow=Nmc) %>% as.annmatrix()
    amp_am =rc %>% {.$amplitude/2} %>% 
      matrix(nrow=Nmc) %>% as.annmatrix()
    acro_am =rc %>% {.$acrophase*2*pi*freq} %>% 
      matrix(nrow=Nmc) %>% as.annmatrix()
  
    pv_am@''            = Xdat@''
    amp_am@''           = Xdat@''
    acro_am@''          = Xdat@''
    pv_am$freq_regr     = freq
    amp_am$freq_regr    = freq
    acro_am$freq_regr   = freq
   
    pv_am_global   = cbind(pv_am_global,pv_am) 
    amp_am_global  = cbind(amp_am_global,amp_am) 
    acro_am_global = cbind(acro_am_global,acro_am) 
  }
  return(list(pvalues = pv_am_global,
              amps    = amp_am_global,
              acros   = acro_am_global))
}