#' Generate a convex programming problem equivalent to power optimization
#' 
#' @description
#' \code{make_problem()} generates a disciplined convex programming problem that is
#' equivalent to maximizing the statistical power of a cosinor-based hypothesis test.
#' The problem is created as a [CVXR::Problem()] which can then be solved using [CVXR]
#' together with the [GUROBI] backend. The [GUROBI] backend is necessary because there
#' are integer constraints on the problem.
#' 
#' @param x a [CVXR::Variable()] representing the weight function for measurement times, see [make_variable()]
#' @param Aquad the symmetric matrix/matrices that define the quadratic form to be optimized, see [make_quadmats()]
#' @param csts a list made up of integer and convex constraints on \code{x}, see [make_constraints()]
#' @param opts a complete set of optimization options, default values can be generated by [make_default_opts()] 
#' 
#' @return \code{prob} a disciplined convex programming problem which can be solved using the [CVXR] library. 
#'  *  See [CVXR::Problem()] for more details on this datatype.
#'  
#' @author Turner Silverthorne
#' @export
make_problem=function(x,Aquad,opts,regL1=0,regFder=0,...){
  # get mean of quad mats and convert to CVXR type
  Amean = 0
  for (ii in c(1:length(Aquad))){
    Amean = Amean + Aquad[[ii]]
    Aquad[[ii]]=Constant(Aquad[[ii]])
  }
  Amean = Amean/length(Aquad)
  Amean = Constant(Amean)
  if(opts$lattice_cstr=='none' & opts$optim_method =='cvxr'){
    Nm   = Constant(opts$Nmeas)
    csts = list( sum(x) == Nm)
    big_str = paste(lapply(1:length(Aquad) %>% as.list(),
           function(ind){
             paste0('quad_form(x,Aquad[[',ind,']])')
           }),collapse=',')
   
    str_prefix='prob=Problem(Minimize('
    str_suffix=paste0('max_elemwise(',big_str,')),csts)')
    
    if(regL1>0){
      regL1 = Constant(regL1)  
      str_prefix=paste0(str_prefix,'regL1*quad_form(x,Amean)+')
    }
    if(regFder>0){
      stop('freq regularization not yet implemented for CVXR')
      #regL1 = Constant(regFder)  
      #str_prefix=paste0(str_prefix,'regFder*quad_form(x,dAdFreq_L2)+')
    }
    
    strp=paset0(str_prefix,str_suffix)
    eval(parse(text=strp))
  }else{
    stop('unrecognized opts$lattice_str or opts$solver_type')
  }
  return(prob)
}