#' Generate vector used in imposing lattice constraints
#'
#' @description
#' Given the constraint matrix and optimization options, \code{make_ineqvec()}
#' generates a vector used in formulating the lattice constraints. 
#' 
#' @param Lmat a matrix of lattice constraints generated by [make_ineqmat()]
#' @param opts a list of optimization options, for instance generated by [make_default_opts()]
#' 
#' @return \code{bvec} a vector used in formulating the lattice constraints
#' * if \code{opts$lattice_cstr=='cfun'} then \code{bvec} is the \code{colSums} of \code{Lmat}
#' * if \code{opts$lattice_cstr=='cfun'} then \code{bvec} is the \code{rowSums} of \code{Lmat}
#' 
#' @author Turner Silverthorne
make_ineqvec=function(Lmat,opts){
  bvec=NaN
  if (opts$lattice_cstr=='cfun'){
    bvec = colSums(Lmat) 
  }else if (opts$lattice_cstr=='lineq'){
    bvec = rowSums(Lmat)
  }else if (opts$lattice_cstr=='none'){
    bvec = NULL
  }
}