#' Generate decision variable for convex power optimization 
#' 
#' @description
#' \code{make_variable()} generates a binary vector which represents the weight function used by CVXR
#' for power optimization.
#' 
#' @param opts optimization options generated by [make_default_opts()]. 
#' * if \code{opts$lattice_cstr=='none'}, \code{x} will have \code{opts$Nfine} components 
#' * if \code{opts$lattice_cstr=='lineq'}, \code{x} will have \code{opts$Nfine} components
#' * if \code{opts$lattice_cstr=='cfun'}, \code{x} will have as many dimensions as there are constraints in \code{Lmat}
#' 
#' In the first two cases, \code{x} represents as a weight function on the candidate measurement times. In the third case,
#' \code{x} represents as a weight function on the candidate sub-lattices.
#' 
#' @param Lmat a matrix containing the lattice constraints, only relevant to this function if \code{opts$lattice_cstr=='cfun'} 
#'   
#' @return \code{x} binary [CVXR::Variable] to be used as the decision variable in CVXR programming.
#' 
#' @author Turner Silverthorne
make_variable=function(opts,Lmat=NULL){
  x=NaN
  if (opts$lattice_cstr=='none' |opts$lattice_cstr=='lineq' ){
    x=Variable(opts$Nfine,boolean=T)
  }else if (opts$lattice_cstr=='cfun'){
    x=Variable(dim(Lmat)[2],boolean=T)
  }
  return(x)
}