#' Cost function for simulated annealing power
#' 
#' @description
#' Evaluates cost function for simulated annealing power optimization.
#' See [run_sa_power()] for details.
#'
#' @param x binary lattice
#' @param Amat symmetric matrix/matrices defining optimization problem, 
#' see [make_quadmats()]
#' @param opts optimization options, generated by [make_default_opts()]
#' 
#' @return value of cost function
#'  
#' @author Turner Silverthorne
sa_cfunpwr=function(x,Amat,opts){
  if (opts$solver_type != 'simulanneal'){
    stop('Wrong solver type, when using sa_cfunpwr, must use opts$solver_type=cvxr')
  }
  if (opts$lattice_cstr%in%c('sa_lattice','none')){
    if (opts$lattice_cstr =='sa_lattice'){
      x=sa_lat2state(x,opts) 
    } 
    if (opts$costfun_type == 'Linfty'){
      if ('list' %in% class(Amat)){
        return(max(unlist(lapply(Amat,function(A){t(x)%*%A%*%x}))))
      }else{
        stop("For Linfty cost fun, Aquad should be a list of matrices not a single matrix")
      }
    }else if(opts$costfun_type=='L1'){
      if ('list' %in% class(Amat)){
        stop("For L1 cost fun, Aquad should be a single matrix not a list of matrices")
      }else{
        return(t(x)%*%Amat%*%x)
      } 
    }else{
      stop('Cost function name not recognized, check opts$costfun_type')
    }
      
  }else{
    stop('Unrecognized lattice constraint. Did you forget to change from CVXR options?')
  }
  
}