#' Convert lattice structure to binary vector representing measurements
#' 
#' @description
#' When using lattice constraints for simulated annealing, the state vector is
#' represented by a list of lattices. This function takes that list and constructs
#' a binary vector of length \code{opts$Nfine} representing the actual state of
#' the system.
#' 
#' This function is mostly used as a helper function for evaluating the simulated 
#' annealing cost function found in [sa_cfunpwr()].
#' 
#' @param x current state of system
#' @param opts optimization options, generated by [make_default_opts()]
#' 
#' 
#' 
#' @author Turner Silverthorne
sa_lat2state=function(x,opts){
  if (opts$lattice_cstr!=sa_lattice){
    warning('You are using the simulated annealing
            lattice to state function on an optimization problem
            without lattice constraints.')
  }
  y = rep(0,opts$Nfine)
  for (ii in 1:length(x)){
    y[x[[ii]]]=y[x[[ii]]]+1
  }
  return(y)
}