#' Convert lattice structure to binary vector representing measurements
#' 
#' @description
#' When using lattice constraints for simulated annealing, the state vector is
#' represented by a list of lattices. This function takes that list and constructs
#' a binary vector of length \code{opts$Nfine} representing the actual state of
#' the system.
#' 
#' This function is mostly used as a helper function for evaluating the simulated 
#' annealing cost function found in [sa_cfunpwr()].
#' 
#' @param x current state of system
#' @param opts optimization options, generated by [make_default_opts()]
#' 
#' @author Turner Silverthorne
#' @export
sa_lat2state=function(x,opts){
  if (class(x)!='list'){
    stop('Input lattice should be a list')
  }
  if (opts$lattice_cstr!='sa_lattice'){
    stop('sa_lat2state should only be called when opts$lattice_cstr==sa_lattice')
  }
  y = rep(0,opts$Nfine)
  for (ii in 1:length(x)){
    xloc = x[[ii]]
    y = y + xloc
  }
  return(y)
}