#' Helper for simulated annealing lattice proposal function
#' 
#' @description
#' Given a list of \code{m} lattices, this function returns a random subset of 
#' the lattices. 
#' 
#'
#' @param \code{m} total number of lattices in current state, see [sa_propfunction()] 
#' @param \code{opts$lprop_method} determines what weighting will be used for
#' sampling a random subset of the lattices. The random subset is generated by
#' first choosing a subset size \code{k<=m} and the sampling \code{k} indices at random.
#' The subset size is determined randomly according to one of the following
#' distributions:
#' \itemize{
#'  \item \code{opts$lprop_method='uniform'} choose \code{k~Unif(1,m)}, 
#'  \item \code{opts$lprop_method='linear'} choose \code{k} with the weighting \code{[m,m-1,...,1]}, meaning that
#'  smaller values of \code{k} are more likely,
#'  \item \code{opts$lprop_method='exp'} choose \code{k} with the weighting \code{[2^{-k}]}
#' }
#' and then subsequent index sampling is always the same, random sampling without
#' replacement.
#' 
#' @return a list of indices which represent the randomly sampled lattices.
#' 
#' @author Turner Silverthorne
#' @export
sa_sample_inds = function(m,opts){
  if (opts$lprop_method=='uniform'){
    ksamp = sample(c(1:m),1)
  }else if(opts$lprop_method=='linear'){
    ksamp = sample(c(1:m),1,prob=c(m:1))
  }else if(opts$lprop_method=='exp'){
    ksamp = sample(c(1:m),1,prob=2^(-c(1:m)))
  }else{
    stop("Unrecognized opts$lprop_method")
  }
  return(sample(c(1:m),size=ksamp,replace=F))
}