solve_2lattice_svdpower_discrete=function(dvar0,freqs,tau,Amp,control,alpha){
x0      = dvar0[['x0']]
N1      = dvar0[['N1']]
N2      = dvar0[['N2']]
dx1     = x0[['dx1']]
dx2     = x0[['dx2']]
xshift2 = x0[['xshift2']]

if (control$optim_method=='simul_anneal'){
  cfun=function(x){
    if (any(is.na(x))){
      stop('NA value in meastimes')
    }else{
      return(1-costfun_2lattice_svdpower_discrete(N1=N1,dx1=x[1],N2=N2,
                                                  dx2=x[2],xshift2=x[3],
                                                  tau=tau,freqs=freqs,
                                                  Amp=Amp,alpha=alpha))
    }
  }
  tfun=function(x){
    if (any(is.na(tau[xinds_from_lat1lat2_pars(N1=N1,dx1=x[1],N2=N2,dx2=x[2],xshift2=x[3])]))){
      stop('NA value generated by pars')
    }else{
      raw=tfun_2lattice_svdpower_discrete(N1=N1,dx1=x[1],N2=N2,dx2=x[2],xshift2=x[3],Nfine=length(tau),control=control)
      return(c(raw$dx1,raw$dx2,raw$xshift2))  
    }
    }
  xopt=stats::optim(x0,fn=cfun,gr=tfun,
                method='SANN',
                control=list(trace  = control$trace,
                             REPORT = control$REPORT,
                             maxit  = control$maxit))
  return(xopt)
}else{stop('unknown control$optim_method')}
}
  